.github/workflows/build-asciidoc.yml
Signed-off-by: RHDH...
sudo make me a sandich
N/A
N/A
=> sudo make me a sandwich

.github/workflows/build-asciidoc.yml, .github/workflows/pr.yml, .gitignore, README.adoc, build/scripts/build.sh
* Create README with contribution, preview, and plugin readme info
* publish branches to a subfolder and collect links to those branches into a root index.html; same for PRs; extract bash code into a build.sh and link from README
=> Create README, push to unique gh-pages folder per branch; extract duplicate code into a build.sh script

build/scripts/build.sh
add section numbers, more trace/error/warnings, and fix the check for adding branches to the index/pulls files
N/A
N/A
=> add section numbers, more trace/error/warnings, and fix the check for adding branches to the index/pulls files

.github/workflows/build-asciidoc.yml, .github/workflows/pr.yml, README.adoc
Signed-off-by: RHDH...
no-op to test GH api
N/A
N/A
=> no-op to test GH api

getting-started/proc-add-custom-app-file-openshift.adoc, getting-started/proc-add-source-control-rhdh-catalog.adoc, getting-started/proc-customize-rhdh-homepage.adoc, installation/proc-install-rhdh-helm.adoc, modules/installation/proc-install-rhdh-helm.adoc
Jira: https://issues.redhat.com/browse/RHIDP-939
Removal of ArtifactHUB: https://issues.redhat.com/browse/RHIDP-1103
=> RHIDP-939: Fix typos and consistency in Getting Started with RHDH doc

getting-started/assembly-auth-provider-github.adoc, getting-started/con-github-app-overview.adoc, getting-started/proc-adding-github-to-frontend.adoc, getting-started/proc-configuring-github-app.adoc, getting-started/proc-registering-github-app.adoc, titles/getting-started-rhdh/title-getting-started.adoc
Associated Jira ticket: RHIDP-1471
=> RHIDP-1471: add GitHub auth provider content

getting-started/con-github-app-overview.adoc
rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED
=> RHIDP-1471: Update overview file ID

build/scripts/build.sh
Reverts redhat-developer/red-hat-developers-documentation-rhdh#100
=> Revert "no op change to test if GPG signing works..."

release-notes/con-relnotes-notable-features.adoc
Purpose: To add context to the cross-refs to make them redirect users to the specific section
=> RHIDP-1037-new: Adding context to the cross-references

artifacts/attributes.adoc, getting-started/proc-add-source-control-rhdh-catalog.adoc, release-notes/con-breaking-changes.adoc, release-notes/con-relnotes-notable-features.adoc, titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
**Purpose**: To resolve this issue: https://issues.redhat.com/browse/RHIDP-1710 [mention that change in the GitHub Organization catalog provider is a breaking change and add cross-references in the new features section for more details]
=> RHIDP-1037-RN: Adding cross-ref in the new features section for more info

modules/rhdh-plugins-reference/ref-rhdh-plugins.adoc
chore: downgrade version of Argo CD front end plugin from 2.6.2 to 2.4.1 (RHIDP-1694, https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1238)
N/A
https://issues.redhat.com/browse/RHIDP-1694
ready to merge in main branch
N/A
=> chore: downgrade version of Argo CD front end plugin from 2.6.2 to 2.4.1 (RHIDP-1694)

getting-started/proc-enable-servicenow-custom-actions-plugin.adoc
@hmanwani-rh here is the cherry pick for 1.0
=> Fixed the service now package to match the correct name

modules/rhdh-plugins-reference/ref-rhdh-plugins.adoc
chore: bump plugin versions in 1.2 (same as in 1.1.1 - RHIDP-1702 / RHIDP-1694)
N/A
same as https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/133 but for main branch
N/A
=> chore: bump plugin versions in 1.2

release-notes/con-relnotes-known-issues.adoc
chore: RHIDP-1734 (RHDH 1.0.z) known-issue and workaround for gitlab token exposure risk #138
N/A
https://issues.redhat.com/browse/RHIDP-1734
N/A
=> chore: RHIDP-1734 (RHDH 1.0.z) known-issue and workaround for gitlab token exposure risk

modules/rhdh-plugins-reference/ref-rhdh-plugins.adoc
chore: bump plugin versions in 1.1.1 - RHIDP-1702 / RHIDP-1694
N/A
* https://issues.redhat.com/browse/RHIDP-1702 
* https://issues.redhat.com/browse/RHIDP-1694
N/A
=> chore: [1.1.x] bump plugin versions in 1.1.1

admin/con-rbac-config-permission-policies-admin.adoc, admin/con-rbac-config-permission-policies-external-file.adoc
Jira: https://issues.redhat.com/browse/RHIDP-1353
=> RHIDP-1353 RBAC enhancements

getting-started/proc-add-custom-app-file-openshift.adoc, getting-started/proc-add-source-control-rhdh-catalog.adoc, installation/proc-install-rhdh-helm.adoc
Purpose: To resolve this issue: https://issues.redhat.com/browse/RHIDP-979
SME review: @rmarting @davidfestal
QE review: @josephca 
Peer review: @linfraze
=> RHIDP-979: Adding YAMl config details to the Helm upgrade procedure

installation/con-rhdh-overview.adoc
When I first looked at RHDH docs, I didn't realise it was based on backstage. It's common for RH products to mention the upstream in the introduction, so making this PR
=> mention backstage

modules/rhdh-plugins-reference/ref-rhdh-plugins.adoc
chore: wrong paths to plugins in supported plugins table
N/A
N/A
=> chore: [main/1.2] wrong paths to plugins in supported plugins table

getting-started/proc-add-source-control-rhdh-catalog.adoc
Fixes https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/issues/120
=> Fix bug #120

admin/con-rbac-rest-api.adoc, admin/proc-rbac-send-request-rbac-rest-api.adoc, admin/proc-rhdh-monitoring-logging-aws.adoc, admin/proc-using-aws-cognito-auth-provider.adoc, artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-readme.adoc, getting-started/proc-add-source-control-rhdh-catalog.adoc, getting-started/proc-configuring-github-app.adoc, getting-started/proc-customize-rhdh-homepage.adoc, getting-started/proc-customize-rhdh-tech-radar-page.adoc, getting-started/proc-registering-github-app.adoc, installation/proc-install-rhdh-operator.adoc
fix: Fixed broken links (#117 backport)
=> fix: Fixed broken links (#117 backport to 1.1.x) 

.github/workflows/build-asciidoc.yml, .github/workflows/pr.yml
chore: bump to latest peaceiris/actions-gh-pages@v4
N/A
N/A
=> chore: bump to latest peaceiris/actions-gh-pages@v4

.github/workflows/build-asciidoc.yml, .github/workflows/pr.yml
chore: replace actions in 1.0 branch with the latest iterations from main (including adding authorization for personal forks)
N/A
N/A
=> chore: replace actions in 1.0 branch with the latest iterations from main (including adding authorization for personal forks)

getting-started/proc-add-source-control-rhdh-catalog.adoc
Manual cherrypick of https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/143/commits/c25d731748c5e5a1d6439be9bec9fae977e34aa7 xref: https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/143
=> [rhdh-1.0] Fix bug #120

admin/proc-rhdh-deploy-aks.adoc, admin/proc-rhdh-deploy-eks-using-helm.adoc, admin/proc-rhdh-deploy-eks-using-operator.adoc, admin/proc-using-aws-cognito-auth-provider.adoc, admin/proc-using-azure-auth-provider.adoc, installation/proc-install-rhdh-operator.adoc, release-notes/con-release-notes-overview.adoc
chore: experiment with attribute expansion in source blocks (#173)
chore: switch to use product-bundle-version and product-chart-version in both simple blocks and those with callouts (use attributes+ to append attribute expansion to default subs list) (#174)
chore: switch to attributes,callouts instead of attributes+; maybe pantheon likes that ? (#175)
chore: more attribute replacements (#176)
chore: another experiment with attributes+ to see if the problem was that I had callouts in other places (#177)
N/A
N/A …
=> chore: attribute + callout expansions in code blocks to reuse variables from attributes.adoc

installation/proc-install-rhdh-operator.adoc
chore: bug: remove doc about how to use custom Backstage image in RHDH operator deployment; this is not supported and should not be encouraged
N/A
N/A
=> chore: [1.1.x] bug: remove doc about how to use custom Backstage image in RHDH operator deployment; this is not supported and should not be encouraged

.github/workflows/build-asciidoc.yml
chore: clean up old closed PRs as well as merged ones
N/A
N/A
=> chore: clean up old closed PRs as well as merged ones

getting-started/proc-add-source-control-rhdh-catalog.adoc
Jira: https://issues.redhat.com/browse/RHIDP-1866
=> RHIDP-1866: GH app id and secret variables updates

installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
**Versions:**
1.1+
**Jira link:**
https://issues.redhat.com/browse/RHIDP-2060
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-196/admin-rhdh/#proc-install-rhdh-airgapped-environment-ocp-helm_admin-rhdh
**Reviews:**
=> RHDIP-2060: Update name reference

artifacts/attributes.adoc, installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
Manual cherrypick of https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/196/commits/807c0ba8a152ecbac486f2d9d723f578baf75934 xref: https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/196
Direct preview link:
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-200/admin-rhdh/#proc-install-rhdh-airgapped-environment-ocp-helm_admin-rhdh
=> [1.1.x] RHDIP-2060: Update name reference

installation/proc-install-rhdh-ocp-operator.adoc
Purpose: To resolve this issue: https://issues.redhat.com/browse/RHIDP-2250
SME review: @gazarenkov 
QE review: @zdrapela
peer review: @hmanwani-rh
=> RHIDP-2250: Removed the optional word for clarity

titles/admin-rhdh/docinfo.xml, titles/installation-rhdh/assemblies, titles/installation-rhdh/docinfo.xml, titles/installation-rhdh/master.adoc
**Versions:**
1.2
**Description:**
Creates the files required to set up the standalone RHDH installation guide
**Associated Jira issue:**
https://issues.redhat.com/browse/RHIDP-1822
**Reviews:**
Peer review:
=> RHIDP-1822: Create an Installing RHDH title in the RHDH repo

assemblies/assembly-auth-provider-oidc.adoc, modules/getting-started/con-oidc-overview.adoc, modules/getting-started/proc-configuring-keycloak-with-oidc.adoc, modules/getting-started/proc-migrating-oauth2-proxy-to-oidc.adoc, titles/getting-started-rhdh/title-getting-started.adoc
=> RHIDP-1890-1-2 Create documentation for OIDC

modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
**Versions:**
1.1+
**Jira link:**
- https://issues.redhat.com/browse/RHIDP-2061
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-244/admin-rhdh/#proc-install-rhdh-ocp-helm_admin-rhdh
**Reviews:**
- QE: N/A, mostly language changes and one small change to the image that was confirmed by SMEs
=> RHIDP-2061: Update image name and other doc improvements

modules/installation/proc-add-custom-app-config-file-ocp.adoc, modules/installation/proc-install-rhdh-ocp-operator.adoc
**Versions:**
1.1+
**Jira link:**
- https://issues.redhat.com/browse/RHIDP-2256
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-249/admin-rhdh/#proc-install-rhdh-ocp-operator_admin-rhdh
**Reviews:**
- SME: N/A
- QE: N/A
=> RHIDP-2256: change Topology tab to view

modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
**Versions:**
1.1+
**Jira link:**
- https://issues.redhat.com/browse/RHIDP-2062
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-247/admin-rhdh/#proc-install-rhdh-airgapped-environment-ocp-helm_admin-rhdh
**Reviews:**
- QE: N/A, small change to a command TBC by SME
=> RHIDP-2062: Align text and code snippet

modules/proc-customizing-the-web-console.adoc
Purpose: To resolve this issue: https://issues.redhat.com/browse/RHIDP-1918
SME review: @jerolimov 
QE review: @zdrapela
Peer review: @Gerry-Forde 
**Cherrypick version**: 1.2.x
PR preview: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-233/getting-started-rhdh/#proc-customizing-the-web-console_rhdh-getting-started
=> RHIDP-1918: updated the customzing theme section for a note

modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
**Versions:**
1.1+
**Jira link:**
- https://issues.redhat.com/browse/RHIDP-2063
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-253/admin-rhdh/#proc-install-rhdh-airgapped-environment-ocp-helm_admin-rhdh
**Reviews:**
- QE: Not required, just removing a line, doesn't really change the content of the docs.
=> RHIDP-2063: Remove not recommended line from docs

modules/installation/ref-rhdh-sizing.adoc, titles/getting-started-rhdh/title-getting-started.adoc
Jira: https://issues.redhat.com/browse/RHIDP-2249
=> RHIDP-2249: Sizing for RHDH

modules/getting-started/ref-additional-rhdh-customizations.adoc
**Versions:**
1.2+
**Jira link:**
- https://issues.redhat.com/browse/RHIDP-2279
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-260/getting-started-rhdh/#ref-additional-rhdh-customizations_rhdh-getting-started
**Reviews:**
=> RHIDP-2279: Document customizing sidebar logo width

modules/release-notes/con-relnotes-notable-features.adoc, titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
chore(deps): update version of Backstage in release notes to use the value from artifacts/attributes.adoc
N/A
N/A
=> chore(deps): update version of Backstage in release notes to use the value from artifacts/attributes.adoc

modules/release-notes/con-relnotes-notable-features.adoc
chore(release notes): add 4 new plugins; remove note about the new operator (it was intro'd in 1.1)
N/A
N/A
=> chore(release notes): add 4 new plugins; remove note about the new operator (it was intro'd in 1.1)

build/scripts/build.sh
chore(build): make console output more legible/usable; fix shellcheck issues
N/A
checkout the repo
run the script: `./build/scripts/build.sh`
=> RHIDP-2841 : chore(build): make console output more legible/usable; fix shellcheck issues

modules/admin/proc-install-operator.adoc
**Versions:**
1.1+
**Jira link:**
- https://issues.redhat.com/browse/RHIDP-1959
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-283/admin-rhdh/#proc-install-operator_admin-rhdh
**Reviews:**
- QE: Not required, no procedural changes
=> RHIDP-1959: Add information about Operator update channels

admin/assembly-admin-templates.adoc
Resolves https://issues.redhat.com/browse/RHIDP-2906
=> RHIDP-2906: Resolve build errors in 1.1 Admin guide

modules/admin/con-rbac-config-permission-policies-external-file.adoc, modules/admin/proc-install-operator.adoc, modules/admin/proc-rbac-send-request-rbac-rest-api.adoc, modules/admin/proc-using-azure-auth-provider.adoc, modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc, modules/release-notes/con-relnotes-notable-features.adoc
=> RHIDP-2908-fix: Fix build errors in Admin guide

modules/release-notes/con-relnotes-notable-features.adoc
Jira: https://issues.redhat.com/browse/RHIDP-2950
=> Scaffolder field extension option

modules/release-notes/con-relnotes-known-issues.adoc
Fixes https://issues.redhat.com/browse/RHIDP-2960
Preview: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-340/rel-notes-rhdh/#con-relnotes-known-issues_release-notes-rhdh
=> docs(known-issues): Document that rollbacks are not supported

.github/pull_request_template.md
1.2+
**Issue:**
https://issues.redhat.com/browse/RHIDP-3008
N/A
**Reviews:**
=> RHIDP-3008: Add docs PR github template

modules/admin/proc-rhdh-deploy-aks-helm.adoc, modules/admin/proc-rhdh-deploy-eks-using-helm.adoc
1.2+
**Issue:**
https://issues.redhat.com/browse/RHIDP-2941
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-347/admin-rhdh/#proc-rhdh-deploy-eks-using-helm_assembly-rhdh-integration-aws
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-347/admin-rhdh/#proc-rhdh-deploy-aks-helm_assembly-rhdh-integration-aks
**Reviews:**
- SME: N/A
- QE: N/A
=> [RHIDP-2941]: Remove italics from code block

modules/admin/con-rbac-config-permission-policies-admin.adoc, modules/admin/con-rbac-config-permission-policies-external-file.adoc, modules/admin/con-rbac-rest-api.adoc, modules/admin/ref-rbac-permission-policies.adoc, modules/admin/ref-rbac-rest-api-endpoints.adoc
Some updates to the RBAC plugin documentation to try to get it caught up with the docs that we have [here](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/rbac-backend/docs) and [here](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/README.md).
- Fixes: [RHIDP-2140](https://issues.redhat.com/browse/RHIDP-2140)
=> RHIDP-2140: updates to rbac documentation

.github/workflows/pr.yml
Reverts redhat-developer/red-hat-developers-documentation-rhdh#277
=> Revert "RHIDP-2842 : chore(gh action): possible fix to pull..."

artifacts/attributes.adoc, modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc, modules/installation/proc-install-rhdh-airgapped-environment-ocp-operator.adoc, modules/installation/proc-installing-rhdh-on-openshift-with-helm-cli.adoc, modules/observability/proc-admin-enabling-metrics-ocp-operator.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-2658
**Link to docs preview:** 
In https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-356/admin-rhdh/  search for "OpenShift CLI (`oc`)".
**Reviews:**
=> RHIDP-2658 Use an attribute for OpenShift CLI (`oc`)

assemblies/assembly-install-rhdh-ocp.adoc, assemblies/assembly-installing-rhdh-on-ocp-by-using-the-helm-chart.adoc, assemblies/assembly-installing-rhdh-on-ocp-by-using-the-operator.adoc, titles/admin-rhdh/title-admin.adoc
We identified that the Platform / Installer / Method pattern is structuring the installation journey:
1. Choose the platform: OCP, AKS, or EKS.
2. Choose the installer: Operator or Helm.
3. Choose the installation method: OCP console or CLI.
The purpose of thispull request is to surface this pattern in the Administration Guide, with as little content change as possible: only move include statements.
1.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-3042
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-351/admin-rhdh/
**Reviews:**
=> RHIDP-3042 - surface the Platform / Installer / Method pattern

modules/admin/con-rbac-config-permission-policies-external-file.adoc, modules/admin/proc-install-operator.adoc, modules/admin/proc-rbac-send-request-rbac-rest-api.adoc, modules/admin/proc-using-azure-auth-provider.adoc, modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc, modules/installation/proc-install-rhdh-ocp-operator.adoc
Reverts redhat-developer/red-hat-developers-documentation-rhdh#361
=> Revert "[1.2.x] RHIDP-3042 - fixed xref statements"

modules/installation/proc-install-rhdh-airgapped-environment-ocp-operator.adoc
chore(deps): fix hardcoded versions in airgap instructions to use the correct latest supported versions from attributes
N/A
[RHIDP-3239](https://issues.redhat.com/browse/RHIDP-3239)
generate content and note that the docs now point to 1.2:
=> chore(deps): fix hardcoded versions in airgap instructions to use the correct latest supported versions from attributes

assemblies/assembly-audit-log.adoc, modules/getting-started/con-audit-log-track-changes-catalog.adoc
1.2.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-3022
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-371/getting-started-rhdh/#con-audit-log-track-changes-catalog_assembly-audit-log
**Reviews:**
Blurb about tracking catalog database changes has also been added to the [RNs draft doc](https://docs.google.com/document/d/1XMhZUKQ0SOMr86mdLiyVTSU0kg4RqtJb8lfoFZ9QRFQ/edit?usp=sharing)
=> RHIDP-3022: Document how to track changes to catalog database

modules/dynamic-plugins/rhdh-supported-plugins.adoc, modules/dynamic-plugins/rhdh-supported-plugins.sh
chore(plugins): remove the -dynamic suffix where it's not used in the dynamic-plugins.default.yaml file ([RHIDP-3203](https://issues.redhat.com/browse/RHIDP-3203))
N/A
[RHIDP-3203](https://issues.redhat.com/browse/RHIDP-3203)
N/A
=> chore(plugins): remove the -dynamic suffix where it's not used in the dynamic-plugins.default.yaml file (RHIDP-3203)

assemblies/assembly-audit-log.adoc
1.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-3332
=> RHIDP-3332-bug-fix: correct attribute

titles/install-rhdh-air-gapped/master.adoc, titles/install-rhdh-aks/master.adoc
Update the title headings for _Installing Red Hat Developer Hub in an air-gapped environment_ and _Installing Red Hat Developer Hub on Azure Kubernetes Service_
=> RHIDP-2510b: Update title headings

artifacts/attributes.adoc
1.2
**Issue:**
[RHIDP-3024](https://issues.redhat.com/browse/RHIDP-3024)
[Release notes](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-380/rel-notes-rhdh/)
**Reviews:**
=> chore(versions): bump chart and operator-bundle to 1.2.2

modules/dynamic-plugins/con-ansible-plugin.adoc, titles/plugin-rhdh/title-plugin.adoc
1.2.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-3467
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-408/plugin-rhdh/#rhdh-ansible
**Reviews:**
Add a section for the Ansible plug-ins and link to AAP docs.
=> RHIDP-3467 Add Ansible plugins to Configuring plugins doc

modules/release-notes/con-relnotes-fixed-issues.adoc
chore: formatting: fix indent so that we have 1.2 and 1.2.2 security fixes under the same section 6.3 (6.3.1, 6.3.2) instead of 6.3.1 and 6.4
N/A
N/A
=> chore: formatting: fix security update indenting

titles/getting-started-rhdh/docinfo.xml
1.2.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-2236
**Reviews:**
=> RHIDP-2236: Update GS guide abstract

titles/install-rhdh-air-gapped/docinfo.xml, titles/install-rhdh-aks/docinfo.xml, titles/install-rhdh-eks/docinfo.xml, titles/install-rhdh-ocp/docinfo.xml
1.2.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-3473
=> RHIDP-3473: Update Install title abstracts

titles/admin-rhdh/title-admin.adoc
Added database assembly to admin guide
https://issues.redhat.com/browse/RHIDP-3475
=> Added database assembly to admin guide

assemblies/assembly-audit-log.adoc, modules/getting-started/con-audit-log-config.adoc, modules/getting-started/proc-audit-log-view.adoc, modules/getting-started/ref-audit-log-catalog-events.adoc, modules/getting-started/ref-audit-log-fields.adoc, modules/getting-started/ref-audit-log-scaffolder-events.adoc
1.2.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-3447
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-407/getting-started-rhdh/#assembly-audit-log
**Reviews:**
=> RHIDP-3447: Audit log doc enhancements

assemblies/assembly-upgrade-rhdh.adoc, modules/installation/proc-install-operator.adoc, modules/upgrade/proc-upgrade-rhdh-helm.adoc, modules/upgrade/proc-upgrade-rhdh-operator.adoc, titles/upgrade-rhdh/docinfo.xml, titles/upgrade-rhdh/master.adoc
Manual cherrypick of [commit 41b9cda]( https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/406/commits/41b9cda521ddbef4a3d156578d614340b1880ab4) from 1.2.x to main
=> RHIDP-3202: Create new adoc files for upgrade content

modules/admin/proc-rbac-send-request-rbac-rest-api.adoc
1.2
**Issue:**
[RHIDP-3297](https://issues.redhat.com/browse/RHIDP-3297)
=> RHIDP-3297: Fix curl policies example

titles/admin-rhdh/title-admin.adoc
Slack thread: https://redhat-internal.slack.com/archives/C06HW0TEQKS/p1722572500336919
=> Added missing section to admin guide

modules/admin/proc-rbac-send-request-rbac-rest-api.adoc
1.3
**Issue:**
[RHIDP-3078](https://issues.redhat.com/browse/RHIDP-3078)
=> RHIDP-3078: Add example curl command for nested conditional policies

assemblies/assembly-customize-rhdh-theme.adoc
RHIDP-3522: Fix docs
1.2+
**Issue:**
https://issues.redhat.com/browse/RHIDP-3522
**Reviews:**
=> chore:fix typo

modules/admin/con-rbac-config-permission-policies-admin.adoc
RHIDP-3522.  
Replace `You can set the credentials ...` to `You can configure`.
1.1
**Issue:**
https://issues.redhat.com/browse/RHIDP-3522
**Reviews:**
=> chore: fix permission doc

titles/rel-notes-rhdh/docinfo.xml
Do not repeat the version in the title to avoid build err…ors in Pantheon
1.3
**Issue:**
https://issues.redhat.com/browse/RHIDP-3566
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-441/rel-notes-rhdh/
**Reviews:**
=> RHIDP-3566: Do not repeat the version in the title 

assemblies/assembly-auth-provider-github.adoc, assemblies/assembly-auth-provider-oidc.adoc
RHIDP-3587 - Use gerund in authorization book chapter titles
1.3
**Issue:**
https://issues.redhat.com/browse/RHIDP-3587
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-444/authorization/
**Reviews:**
=> RHIDP-3587 - Use gerund in authorization book chapter titles

artifacts/attributes.adoc
=> chore: tagRelease.sh: bump to 1.4.0 in main branch

modules/installation/proc-rhdh-deploy-eks-helm.adoc
=> RHIDP-3480 fixes typo

artifacts/attributes.adoc, modules/release-notes/con-relnotes-fixed-issues.adoc
chore(release-notes): add CVE fixes for the 1.2.3 upcoming release - RHIDP-3688 RHIDP-3689
bump operator and chart version to 1.2.3; also fix minimum OCP version to align to https://access.redhat.com/support/policy/updates/developerhub
N/A
See issues in 1.2.3: https://issues.redhat.com/projects/RHIDP/versions/12431228
https://issues.redhat.com/browse/RHIDP-3699 is the doc issue for this change. 
N/A
=> chore(release-notes): add CVE fixes for the 1.2.3 upcoming release

modules/admin/con-rbac-config-permission-policies-external-file.adoc, modules/admin/proc-configuring-postgresql-instance-using-helm.adoc, modules/admin/proc-using-aws-cognito-auth-provider.adoc, modules/installation/proc-install-rhdh-ocp-helm-gui.adoc, modules/proc-create-plugin.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-3484
**Reviews:**
=> Rhidp 3484 global fix of source tags

modules/installation/proc-deploy-rhdh-instance-eks.adoc, modules/installation/proc-rhdh-deploy-aks-helm.adoc, modules/installation/proc-rhdh-deploy-eks-helm.adoc, modules/installation/proc-rhdh-deploy-eks-operator.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-3484
**Reviews:**
=> RHIDP 3484-01-Global-Fix-of-Source-Tags

artifacts/rhdh-plugins-reference/argocd/argocd-plugin-readme.adoc, assemblies/assembly-add-custom-app-file-openshift.adoc, modules/admin/proc-configuring-postgresql-instance-using-helm.adoc, modules/admin/proc-configuring-postgresql-instance-using-operator.adoc, modules/admin/proc-migrating-databases-to-an-external-server.adoc, modules/dynamic-plugins/proc-rhdh-example-external-dynamic-plugins.adoc, modules/dynamic-plugins/proc-using-custom-npm-registry.adoc, modules/dynamic-plugins/ref-example-dynamic-plugin-helm-installations.adoc, modules/getting-started/proc-add-source-control-rhdh-catalog.adoc, modules/getting-started/proc-customize-rhdh-homepage.adoc, modules/getting-started/proc-enable-servicenow-custom-actions-plugin.adoc, modules/getting-started/proc-techdocs-publish-site.adoc, modules/getting-started/ref-techdocs-example-config-plugin-operator.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-3484
**Reviews:**
=> RHIDP 3484 Fix Syntax Highlighting

artifacts/attributes.adoc, modules/dynamic-plugins/con-ansible-plugin.adoc
PR title format: Adding attributes for Installation Guides
IMPORTANT: Do Not Merge - To be merged by Docs Team Only
**Version(s):** 1.2, 1.3
**Issue:** RHIDP-3968
**Reviews:**
=> added the required attributes - rhidp-3968

assemblies/assembly-configuring-authorization-in-rhdh.adoc, modules/admin/con-rbac-conditional-policies-rhdh.adoc, modules/admin/proc-rbac-config-conditional-policy-file.adoc
RHIDP-3425 3426: RBAC conditional policies in 1.3
1.3
**Issue:**
[RHIDP-3425](https://issues.redhat.com/browse/RHIDP-3425)
[RHIDP-3426](https://issues.redhat.com/browse/RHIDP-3426)
**Reviews:**
=> RHIDP-3425 3426: RBAC conditional policies in 1.3

modules/getting-started/proc-add-source-control-rhdh-catalog.adoc
**Version(s):** 1.2 
**Issue:** https://issues.redhat.com/browse/RHIDP-3990
**Reviews:**
=> removing incorrect references

.github/workflows/build-asciidoc.yml, .github/workflows/pr.yml
replace local references to owner/repo  with github.repository_owner and github.event.repository.name; if this doesn't work from forks, then we can hardcode the values
N/A
N/A
=> chore: replace local references to owner/repo

.github/workflows/pr.yml
Signed-off-by: Nick Boldt...
chore:typo
N/A
N/A
=> chore:typo

artifacts/attributes.adoc
PR title format: Manual cherry pick from #491 to 1.2.x
=> [Manual CP for PR-491 (1.2.x)] added the required attributes - rhidp-3968

assemblies/assembly-enabling-authentication.adoc
Backport for 1.3 https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/460
=> RHIDP-3794 - update Authentication book introduction (#460)

modules/installation/proc-install-rhdh-osd-gcp-helm.adoc, modules/installation/proc-install-rhdh-osd-gcp-operator.adoc
Fixed link in OSD-GCP doc
1.3
**Issue:**
Find within the PR
**Reviews:**
=> Fixed link in OSD GCP doc

assemblies/assembly-audit-log.adoc, modules/getting-started/ref-audit-log-file-rotation-overview.adoc
RHIDP-3836 Audit log: Audit log changes for RHDH 1.3
1.3
**Issue:**
https://issues.redhat.com/browse/RHIDP-3836
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-486/getting-started-rhdh/#ref-audit-log-file-rotation-overview_assembly-audit-log
**Reviews:**
Not all SMEs and QEs have permissions to give approving reviews. SME and QE reviews are required, but they may not count as "approved reviews" based on doc repo structure. Still have SME and QE review, but note that the red X for "3 approved reviews" may still appear.
=> RHIDP-3836 Audit log: Audit log changes for RHDH 1.3

modules/release-notes/con-relnotes-notable-features.adoc, modules/release-notes/con-relnotes-techpreview-features.adoc
chore: fix links from RN -> Plugins guide (RHIDP-3187)
N/A
N/A
=> chore: fix links from RN -> Plugins guide (RHIDP-3187)

modules/admin/proc-rhdh-deployment-config.adoc, titles/admin-rhdh/title-admin.adoc
RHIDP-3728 [Docs] Document Deployment customization configuration for Operator
1.3+
**Issue:**
https://issues.redhat.com/browse/RHIDP-3728
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-496/admin-rhdh/#proc-rhdh-deployment-config_assembly-admin-templates
**Reviews:**
Not all SMEs and QEs have permissions to give approving reviews. SME and QE reviews are required, but they may not count as "approved reviews" based on doc repo structure. Still have SME and QE review, but note that the red X for "3 approved reviews" may still appear.
=> RHIDP-3728 [Docs] Document Deployment customization configuration for Operator

titles/admin-rhdh/title-admin.adoc
**Version(s):** main, 1.3
**Issue:** RHIDP-4202
**Reviews:**
=> RHIDP-4202: Adding missing modules to the main branch

assemblies/dynamic-plugins/assembly-rhdh-installing-dynamic-plugins.adoc, modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc, modules/dynamic-plugins/ref-rh-compatible-plugins.adoc, titles/plugins-rhdh-reference/docinfo.xml, titles/plugins-rhdh-reference/master.adoc
=> RHIDP-3440-reference 1.3 Add tables

titles/plugins-rhdh-about/master.adoc
1.3
**Issue:**
RHIDP-4330 About content
**Reviews:**
=> RHIDP-3440-about-1 Resolve merge conflicts

modules/getting-started/proc-adding-github-to-frontend.adoc
chore(broken link): fix link to https://github.com/janus-idp/backstage-showcase/blob/main/docs/auth.md#enabling-authentication-in-showcase RHIDP-4294
N/A
[RHIDP-4294](https://issues.redhat.com/browse/RHIDP-4294)
N/A
=> chore(broken link): fix link to https://github.com/janus-idp/backstage-showcase/blob/main/docs/auth.md#enabling-authentication-in-showcase RHIDP-4294

artifacts/attributes.adoc, artifacts/rhdh-plugins-reference/argocd/argocd-plugin-admin.adoc, assemblies/assembly-release-notes-breaking-changes.adoc, modules/release-notes/snip-removed-functionality-rhidp-3187.adoc, modules/release-notes/snip-removed-functionality-rhidp-4293.adoc
chore: add missing content about renamed plugins; fix links to the new books and remove hardcoded link to 1.2 docs (RHIDP-4293)
N/A
https://issues.redhat.com/browse/RHIDP-4293
N/A
=> chore: add missing content about renamed plugins; fix links to the new books and remove hardcoded link to 1.2 docs (RHIDP-4293)

artifacts/attributes.adoc, artifacts/rhdh-plugins-reference/argocd/argocd-plugin-admin.adoc, assemblies/assembly-release-notes-breaking-changes.adoc, modules/release-notes/snip-removed-functionality-rhidp-3187.adoc, modules/release-notes/snip-removed-functionality-rhidp-4293.adoc
Backport https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/570
=> Cherry pick #570

artifacts/rhdh-plugins-reference/argocd/argocd-plugin-user.adoc, artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-user.adoc, artifacts/rhdh-plugins-reference/nexus-repository-manager/nexus-repository-manager-plugin-user.adoc, artifacts/rhdh-plugins-reference/tekton/tekton-plugin-user.adoc, assemblies/dynamic-plugins/assembly-using-rhdh-plugins.adoc, modules/dynamic-plugins/con-ansible-plugin-user.adoc, modules/dynamic-plugins/proc-using-topology-plugin.adoc, titles/plugins-rhdh-using/docinfo.xml, titles/plugins-rhdh-using/master.adoc
=> RHIDP-3440 Manual cherrypick of Using Dynamic Plugins

artifacts/attributes.adoc
1.3
**Issue:**
Fix broken linking Dynamic Plugins Guide - **Only applies to release-1.3 branch**
**Reviews:**
=> RHIDP-3440 Fix broken link in Dynamic Plugins Reference

modules/getting-started/proc-customize-rhdh-homepage.adoc, modules/getting-started/proc-customize-rhdh-learning-paths.adoc, modules/installation/proc-rhdh-deploy-eks-operator.adoc
Doc issue fixes
1.2, 1.3
**Issue:**
[RHIDP-4050](https://issues.redhat.com/browse/RHIDP-4050)
[RHIDP-4099](https://issues.redhat.com/browse/RHIDP-4099)
Find the link within this PR
**Reviews:**
=> RHIDP-4050, 4099: Fix doc issues

modules/getting-started/con-techdocs-config-cicd.adoc
**Version(s):** 1.2, 1.3
**Issue:** RHIDP-3887
**Reviews:**
=> RHIDP-3887: Fixing a typo

modules/dynamic-plugins/proc-using-topology-plugin.adoc
1.3+
**Issue:**
**Reviews:**
Typo - does not require reviews/approvals other than by the (merge) gatekeeper.
=> RHIDP-4330 - Topology plugin updates

modules/admin/ref-rbac-rest-api-endpoints.adoc
Format user-replaced values consitently according to https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values
**Version(s):** 1.3 
**Issue:** https://issues.redhat.com/browse/RHIDP-4332
**Link to docs preview:** https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-584/authorization/
**Reviews:**
=> RHIDP-4332 - Formatted user-replaced values

modules/getting-started/proc-customize-rhdh-homepage.adoc
RHIDP-4187 [DOC] Getting Started >Customizing the Home Page 4.1 and 4.2 header update
1.2+
**Issue:**
https://issues.redhat.com/browse/RHIDP-4187
4.1: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-577/getting-started-rhdh/#_using-hosted-json-files-to-provide-data-to-the-home-page
4.2: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-577/getting-started-rhdh/#_using-a-dedicated-service-to-provide-data-to-the-home-page
**Reviews:**
=> RHIDP-4187 [DOC] Getting Started >Customizing the Home Page 4.1 and 4.2 header update

assemblies/assembly-add-custom-app-file-openshift.adoc, modules/installation/proc-install-rhdh-osd-gcp-helm.adoc
**Version(s):** 1.3
**Issue:** RHIDP-4329 and RHIDP-4331
**Review:**
=> RHIDP-4329 and RHIDP-4331: Deferencing code blocks

modules/authentication/proc-provisioning-users-from-microsoft-azure-to-the-software-catalog.adoc
=> chore: fixed typos

assemblies/assembly-release-notes-breaking-changes.adoc, assemblies/assembly-release-notes-known-issues.adoc, modules/release-notes/single-source-release-notes.py, modules/release-notes/snip-known-issue-rhidp-4378.adoc, modules/release-notes/snip-removed-functionality-rhidp-3074.adoc, modules/release-notes/snip-removed-functionality-rhidp-3187.adoc
* Update release notes.
* Fixed script deleting too many files.
* Moved script in the same directory as the release notes and the other release notes script.
**Issue:**
**Reviews:**
=> chore: update release notes

modules/installation/proc-add-custom-app-config-file-ocp-operator.adoc, modules/installation/proc-deploy-rhdh-instance-eks.adoc, modules/installation/proc-rhdh-deploy-aks-operator.adoc
**Version(s):** 1.3.1
**Issue:** https://issues.redhat.com/browse/RHIDP-3111
**Reviews:**
=> RHIDP-3111 Replace references to deprecated backend.auth.keys config

modules/authentication/proc-creating-a-custom-transformer-to-provision-users-from-rhsso-to-the-software-catalog.adoc
=> fix duplicate id

modules/importing-repositories/procedure-understanding-bulk-import-audit-logs.adoc
=> fix listing block

modules/dynamic-plugins/con-ansible-plugin.adoc
**Version(s):** 1.2.x
[This has to be done for 1.3.x too but it's already done in PR-491
**Issue:** RHIDP-3714
**Reviews:**
=> RHIDP-3714: Fixed typo

modules/authorization/proc-mounting-the-policy-csv-file-using-the-operator.adoc
**Version(s):** 1.2, 1.3
**Issue:** RHIDP-4090
**Reviews:**
=> RHIDP-4090: Fixed typo

artifacts/attributes.adoc, modules/installation/proc-install-operator.adoc
**Version(s):** 1.4 only!
[I will manually cherrypick the 2nd and 3rd commit to 1.3.x] - for RHIDP-4660
**Issue:** RHIDP-4725
**Reviews:**
=> RHIDP-4725: Update OCP supported versions for 1.4

modules/installation/proc-add-custom-app-config-file-ocp-operator.adoc
Manual CP from PR-695 to 1.3.x
PR-716 - auto-cherrypicking failed.
=> Manual Cherrypicking PR-695

artifacts/attributes.adoc
Attribute updated in 1.3 branch
=> Updated 1.3 attribute

artifacts/attributes.adoc, modules/about/ref-supported-platforms.adoc
**Issue:** 
https://issues.redhat.com/browse/RHIDP-4699
Related PR: https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/661
=> Add supported platform

assemblies/assembly-about-rhdh.adoc, modules/about/ref-rhdh-sizing.adoc, titles/about/master.adoc
**Version(s):** 1.3, 1.4
**Issue:** RHIDP-4996
=> RHIDP-4996- Adds sizing requirements 

modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
=> RHIDP-3490-Updates the context

titles/about/master.adoc
The title is already defined in the assembly (consistent with other titles).
Fixes the build in Pantheon.
**Issue:**
=> fix: No duplicate title

modules/installation/proc-install-rhdh-airgapped-environment-ocp-operator.adoc
Manual cherrypicking for PR-741
=> Manual cherrypicking for PR-741

artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc
**Version(s):** 1.3
**Issue:** https://issues.redhat.com/browse/RHIDP-3060
=> Add supported keycloak version

artifacts/attributes.adoc, artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-3060
=> Add keycloak plugin 1.4

modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
=> Sanity check 1.4 title

modules/release-notes/single-source-release-notes-template.adoc.jinja
=> fix release-notes template formatting

assemblies/dynamic-plugins/assembly-configuring-rhdh-plugins.adoc, modules/dynamic-plugins/con-overriding-core-backend-services.adoc
RHIDP-4802-1-4 Manual cherrypick of PR-766
1.4
**Issue:**
RHIDP-4802-1-4 - Dynamic plugin: Document how users can add middleware functions to proxy backend
=> RHIDP-4802-1-4 Manual cherrypick of PR-766

modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
Updated the container version in the airgap with helm procedure
**Version(s):** 1.3, 1.4 
**Issue:** https://issues.redhat.com/browse/RHDHBUGS-137
=> RHDHBUGS-137 fix the container version in the airgap with helm procedure

modules/authorization/proc-enabling-the-rbac-plugin.adoc
1.4
**Issue:**
https://issues.redhat.com/browse/RHIDP-5349
=> RHIDP-5349: incorrect ID of RBAC plugin

artifacts/rhdh-plugins-reference/acr/acr-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/jfrog-artifactory/jfrog-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc, artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-readme.adoc, artifacts/rhdh-plugins-reference/nexus-repository-manager/nexus-repository-manager-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/nexus-repository-manager/nexus-repository-manager-plugin-admin.adoc, artifacts/rhdh-plugins-reference/nexus-repository-manager/nexus-repository-manager-plugin-readme.adoc, artifacts/rhdh-plugins-reference/ocm/ocm-backend-plugin-readme.adoc, artifacts/rhdh-plugins-reference/ocm/ocm-common-plugin-readme.adoc, artifacts/rhdh-plugins-reference/quay/quay-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/tekton/tekton-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/tekton/tekton-plugin-admin.adoc, artifacts/rhdh-plugins-reference/tekton/tekton-plugin-readme.adoc, artifacts/rhdh-plugins-reference/topology/topology-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/topology/topology-plugin-readme.adoc, modules/authorization/proc-enabling-the-rbac-plugin.adoc, modules/dynamic-plugins/proc-topology-install.adoc, modules/importing-repositories/procedure-enabling-the-bulk-import-from-github-feature.adoc, modules/observe/proc-disabling-telemetry-using-helm.adoc, modules/observe/proc-disabling-telemetry-using-operator.adoc, modules/observe/proc-enabling-telemetry-using-helm.adoc, modules/observe/proc-enabling-telemetry-using-operator.adoc, modules/using-service-now/proc-enable-servicenow-custom-actions-plugin.adoc
Continuation of https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/824. This PR updates references to plugins to use their new locations
**Issue:** https://issues.redhat.com/browse/RHIDP-4853
=> chore: update migrated plugins locations

artifacts/rhdh-plugins-reference/acr/acr-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/jfrog-artifactory/jfrog-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc, artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-readme.adoc, artifacts/rhdh-plugins-reference/nexus-repository-manager/nexus-repository-manager-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/nexus-repository-manager/nexus-repository-manager-plugin-admin.adoc, artifacts/rhdh-plugins-reference/nexus-repository-manager/nexus-repository-manager-plugin-readme.adoc, artifacts/rhdh-plugins-reference/ocm/ocm-backend-plugin-readme.adoc, artifacts/rhdh-plugins-reference/ocm/ocm-common-plugin-readme.adoc, artifacts/rhdh-plugins-reference/quay/quay-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/tekton/tekton-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/tekton/tekton-plugin-admin.adoc, artifacts/rhdh-plugins-reference/tekton/tekton-plugin-readme.adoc, artifacts/rhdh-plugins-reference/topology/topology-install-dynamic-plugin.adoc, artifacts/rhdh-plugins-reference/topology/topology-plugin-readme.adoc, modules/dynamic-plugins/proc-topology-install.adoc, modules/importing-repositories/procedure-enabling-the-bulk-import-from-github-feature.adoc, modules/observe/proc-disabling-telemetry-using-helm.adoc, modules/observe/proc-disabling-telemetry-using-operator.adoc, modules/observe/proc-enabling-telemetry-using-helm.adoc, modules/observe/proc-enabling-telemetry-using-operator.adoc, modules/using-service-now/proc-enable-servicenow-custom-actions-plugin.adoc
Cherrypick of https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/825. This PR updates references to plugins to use their new locations. 
**Issue:**
https://issues.redhat.com/browse/RHIDP-4853
=> [release-1.4] RHIDP-4853: update migrated plugins locations

modules/release-notes/ref-release-notes-breaking-changes.adoc
**RHIDP-5367 - Missing and incorrect information in "breaking changes"**
1.4
**Issue:**
[RHIDP-5367](https://issues.redhat.com/browse/RHIDP-5368)
=> RHIDP-5367 - Missing and incorrect information in "breaking changes"

modules/authorization/proc-enabling-the-rbac-plugin.adoc
**Version(s):** 1.4, main
**Issue:** RHIDP-5456
=> RHIDP-5456: Updated broken link Authorization Guide

README.adoc
chore: remove reference to RHIDP-451 as we have closed it as obsolete
N/A
https://issues.redhat.com/browse/RHIDP-451
N/A
=> chore: remove reference to RHIDP-451 as we have closed it as obsolete

modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc, modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths.adoc, modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc, modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
chore(migration): move from janus-idp/backstage-showcase to redhat-developer/rhdh and add more plugin repo links too (RHIDP-1022)
N/A
https://issues.redhat.com/browse/RHIDP-1022
N/A
=> chore(migration): move from janus-idp/backstage-showcase to redhat-developer/rhdh and add more plugin repo links too (RHIDP-1022)

modules/authorization/proc-enabling-the-rbac-plugin.adoc
**Version(s):** 1.3, 1.4, 1.5
**Issue:** https://issues.redhat.com/browse/RHIDP-4840
=> RHIDP-4840 - Fix broken link

artifacts/rhdh-plugins-reference/argocd/argocd-plugin-readme.adoc, artifacts/rhdh-plugins-reference/argocd/argocd-plugin-user.adoc
**Version(s):**  1.3 
**Issue:** https://issues.redhat.com/browse/RHIDP-4345
=> Fix attribute typo in Argo CD plugin

assemblies/assembly-about-rhdh.adoc, modules/about/con-integrations-in-rhdh.adoc, modules/about/ref-customer-support-info.adoc, modules/about/ref-supported-platforms.adoc, titles/about/master.adoc
**Version(s):** 1.3 
**Issue:** RHIDP-5070
=> Updates the about guide

modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc
**Version(s):** 1.3 1.4 1.5
**Issue:** https://issues.redhat.com/browse/RHIDP-5334
=> RHIDP-5334 - Fix rbac-policies mount path for Helm

modules/installation/proc-install-operator.adoc, modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc, modules/installation/proc-install-rhdh-airgapped-environment-ocp-operator.adoc, modules/installation/proc-install-rhdh-ocp-helm-cli.adoc, modules/installation/proc-install-rhdh-ocp-helm-gui.adoc, modules/installation/proc-install-rhdh-ocp-operator.adoc, modules/observe/con-audit-log-config.adoc, modules/observe/proc-admin-enabling-metrics-ocp-helm.adoc, modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc, modules/upgrade/proc-upgrade-rhdh-operator.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-5396
=> Replace links to docs.openshift.com

artifacts/attributes.adoc
chore: bump main to RHDH 1.5, BS 1.35, and OCP 4.18
Signed-off-by: rhdh-bot service account <rhdh-bot@redhat.com>
N/A
N/A
=> chore: bump main to RHDH 1.5, BS 1.35, and OCP 4.18

modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
**Version(s):** 1.4.x
**Issue:**
[RHIDP-5643](https://issues.redhat.com/browse/RHIDP-5643)
=> RHIDP-5643: Fix capitalization error

modules/authentication/proc-enabling-authentication-with-rhbk.adoc, modules/release-notes/ref-release-notes-known-issues.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-4695
=> [release-1.4] update RHBK config docs with security consideration

modules/authentication/proc-enabling-authentication-with-rhbk.adoc
**Issue:**
Manual cherry-pick of https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/869
=> manual cherrypick of update RHBK config docs with security consideration

modules/about/ref-supported-platforms.adoc
**This PR removes the link redirecting to the Compatibility Matrix until we finalize its inclusion in the Release Notes.**
Cherry-pick to 1.3 to apply the same changes. 
**Version(s):** 1.4, 1.3
**Issue:** https://issues.redhat.com/browse/RHIDP-5070
=> Remove link to Compatibility matrix

artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc
This change applies to 1.4. 
**Issue:** https://issues.redhat.com/browse/RHIDP-5672
=> Add the correct reference to product

modules/dynamic-plugins/proc-installing-and-configuring-redis-cache.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-5185
=> RHIDP-5004 remove useRedisSets

modules/release-notes/snip-fixed-security-issues-in-product-1.3.0.adoc, modules/release-notes/snip-fixed-security-issues-in-rpm-1.3.0.adoc, modules/release-notes/snip-fixed-security-issues-in-rpm-1.3.1.adoc
Folluw-up for https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/908
**Version(s):** 1.3
**Issue:**
=> Update CVE content for release-1.3

modules/authentication/proc-enabling-authentication-with-github.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-5765
=> RHIDP-5765 comment out references to GitHub Enterprise

modules/configuring-deployment/proc-configuring-deployment-by-using-the-operator.adoc, modules/dynamic-plugins/con-dynamic-plugins-cache.adoc
1.5, main, 1.4.x
**Issue:**
[RHIDP-5544](https://issues.redhat.com/browse/RHIDP-5544)
=> RHIDP-5544: Changed alpha2 to alpha3 API in docs

modules/installation/proc-install-rhdh-airgapped-environment-ocp-operator.adoc
chore: bad link in code snippet points to non-existent branch
N/A
https://issues.redhat.com/browse/RHIDP-3206?focusedId=26593580&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26593580
N/A
=> chore: bad link in code snippet points to non-existent branch (RHIDP-3206)

modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc, modules/configuring-external-databases/proc-migrating-databases-to-an-external-server.adoc, modules/dynamic-plugins/proc-create-plugin-tgz-file.adoc, modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
1.4.x
**Issue:**
[RHIDP-3206](https://issues.redhat.com/browse/RHIDP-3206)
**Preview links for two instances:**
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-945/configuring/#proc-configuring-postgresql-instance-using-helm_configuring-external-postgresql-databases
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-945/configuring/#proc-migrating-databases-to-an-external-server_configuring-external-postgresql-databases
=> RHIDP-3206: Added missing attribute declaration in the source code

assemblies/assembly-configuring-readonlyrootfilesystem.adoc, modules/configuring-readonlyrootfilesystem/proc-configuring-readonlyrootfilesystem-option-in-rhdh-helm-chart-deployment.adoc, modules/configuring-readonlyrootfilesystem/proc-configuring-readonlyrootfilesystem-option-in-rhdh-operator-deployment.adoc, modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc, modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc, titles/configuring/master.adoc
main, 1.5
**Issue:**
[RHIDP-5901](https://issues.redhat.com/browse/RHIDP-5901)
**Preview link:** https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-938/configuring/#readonlyrootfilesystem
=> RHIDP-5901: readOnlyRootFilesystem option

modules/release-notes/ref-release-notes-technology-preview.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-5768
Preview: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-950/rel-notes-rhdh/#technology-preview-rhidp-5545
=> RHIDP-5768: Fix typo in 1.4 docs

modules/authentication/proc-enabling-authentication-with-github.adoc, modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc, modules/authentication/proc-enabling-authentication-with-rhbk.adoc, modules/authentication/proc-provisioning-users-from-github-to-the-software-catalog.adoc, modules/authentication/proc-provisioning-users-from-microsoft-azure-to-the-software-catalog.adoc, modules/authentication/proc-provisioning-users-from-rhbk-to-the-software-catalog.adoc
* Update dangerouslyAllowSignInWithoutUserInCatalog config according to https://github.com/redhat-developer/rhdh/pull/2354. 
* Fix formatting.
* Simplify code sample presentation.
**Issue:** https://issues.redhat.com/browse/RHIDP-5959
=> RHIDP-5959 Update dangerouslyAllowSignInWithoutUserInCatalog config

modules/authentication/proc-enabling-authentication-with-github.adoc, modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc, modules/authentication/proc-enabling-authentication-with-rhbk.adoc, modules/authentication/proc-provisioning-users-from-github-to-the-software-catalog.adoc, modules/authentication/proc-provisioning-users-from-microsoft-azure-to-the-software-catalog.adoc, modules/authentication/proc-provisioning-users-from-rhbk-to-the-software-catalog.adoc
Cherry-pick https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/978  to the release-1.5 branch.
=> [release-1.5] RHIDP-5959 Update dangerouslyAllowSignInWithoutUserInCatalog config 

modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc, modules/dynamic-plugins/proc-install-plugins-using-custom-npm-registry.adoc, modules/dynamic-plugins/proc-load-plugin-js-package.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-6130
=> RHIDP-6130: Update docs to refer to new secret name

modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc, modules/configuring/proc-provisioning-your-custom-configuration.adoc, modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc, modules/customizing/proc-customizing-the-backend-secret.adoc, modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc, modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc, modules/installation/proc-deploy-rhdh-instance-eks.adoc, modules/installation/proc-deploy-rhdh-instance-gke.adoc, modules/installation/proc-rhdh-deploy-aks-operator.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-5881
=> RHIDP-5881: Fix inconsistencies with referencing my-rhdh-secrets #944

modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc, modules/configuring/proc-provisioning-your-custom-configuration.adoc, modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc, modules/customizing/proc-customizing-the-backend-secret.adoc, modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc, modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc, modules/installation/proc-deploy-rhdh-instance-eks.adoc, modules/installation/proc-deploy-rhdh-instance-gke.adoc, modules/installation/proc-rhdh-deploy-aks-operator.adoc
**Issue:**
https://issues.redhat.com/browse/RHIDP-5881
=> Rhidp 5881: Manual cherry-pick944.1.4

modules/authentication/proc-enabling-authentication-with-github.adoc, modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc, modules/authorization/proc-configuring-the-RBAC-backend-plugin.adoc, modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc, modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc, modules/authorization/proc-enabling-the-rbac-plugin.adoc, modules/authorization/proc-setting-up-the-guest-authentication-provider.adoc, modules/customizing-templates/proc-adding-templates.adoc, modules/customizing-the-appearance/proc-customize-rhdh-branding-logo.adoc, modules/customizing-the-appearance/proc-customize-rhdh-font.adoc, modules/customizing-the-appearance/proc-customize-rhdh-page-theme.adoc, modules/customizing-the-appearance/proc-customize-rhdh-palette.adoc, modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc, modules/customizing-the-appearance/proc-loading-custom-theme-using-dynamic-plugin.adoc, modules/customizing-the-appearance/ref-customize-rhdh-custom-components.adoc, modules/customizing-the-appearance/ref-customize-rhdh-default-backstage.adoc, modules/customizing-the-appearance/ref-customize-rhdh-default-rhdh.adoc, modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc, modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc, modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths.adoc, modules/customizing-the-quick-access-card/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc, modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc, modules/customizing-the-tech-radar-page/proc-customize-rhdh-tech-radar-page.adoc, modules/dynamic-plugins/con-install-dynamic-plugin-helm.adoc, modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc, modules/dynamic-plugins/ref-example-dynamic-plugin-helm-installations.adoc, modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc, modules/installation/proc-deploy-rhdh-instance-eks.adoc, modules/installation/proc-deploy-rhdh-instance-gke.adoc, modules/installation/proc-rhdh-deploy-aks-operator.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-5372
=> RHIDP-5372- Fix inconsistent reference to the app config file (#914)

modules/authentication/proc-enabling-authentication-with-github.adoc, modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc, modules/authorization/proc-configuring-the-RBAC-backend-plugin.adoc, modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc, modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc, modules/authorization/proc-enabling-the-rbac-plugin.adoc, modules/authorization/proc-setting-up-the-guest-authentication-provider.adoc, modules/customizing-templates/proc-adding-templates.adoc, modules/customizing-the-appearance/proc-customize-rhdh-branding-logo.adoc, modules/customizing-the-appearance/proc-customize-rhdh-font.adoc, modules/customizing-the-appearance/proc-customize-rhdh-page-theme.adoc, modules/customizing-the-appearance/proc-customize-rhdh-palette.adoc, modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc, modules/customizing-the-appearance/proc-loading-custom-theme-using-dynamic-plugin.adoc, modules/customizing-the-appearance/ref-customize-rhdh-custom-components.adoc, modules/customizing-the-appearance/ref-customize-rhdh-default-backstage.adoc, modules/customizing-the-appearance/ref-customize-rhdh-default-rhdh.adoc, modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc, modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc, modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths.adoc, modules/customizing-the-quick-access-card/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc, modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc, modules/customizing-the-tech-radar-page/proc-customize-rhdh-tech-radar-page.adoc, modules/dynamic-plugins/con-install-dynamic-plugin-helm.adoc, modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc, modules/dynamic-plugins/ref-example-dynamic-plugin-helm-installations.adoc, modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc, modules/installation/proc-deploy-rhdh-instance-eks.adoc, modules/installation/proc-deploy-rhdh-instance-gke.adoc, modules/installation/proc-rhdh-deploy-aks-operator.adoc
**Issue:**  https://issues.redhat.com/browse/RHIDP-5372
=> RHIDP-5372- Manual cherry-pick-1.4-Fix inconsistent reference to the app config file#914

assemblies/dynamic-plugins/assembly-extensions-plugins.adoc, modules/dynamic-plugins/con-catalog-searching-and-filtering.adoc, modules/dynamic-plugins/proc-catalog-viewing.adoc, modules/dynamic-plugins/proc-extensions-creating.adoc, modules/dynamic-plugins/proc-extensions-disabling.adoc, modules/dynamic-plugins/proc-extensions-managing.adoc, modules/dynamic-plugins/proc-viewing-installed-plugins.adoc, modules/dynamic-plugins/ref-catalog-plugin.adoc, titles/plugins-rhdh-install/master.adoc
This is a manual cherry-pick of #995 
main
**Issue:**
[RHIDP-3393](https://issues.redhat.com/browse/RHIDP-3393)
=> RHIDP-3393-1 - Document how users can access Plugin Marketplace in RHDH

modules/observe/adoption-insights/proc-setting-duration-of-data-metrics.adoc
1.5, main
**Issue:**
RHDHPAI-716
=> RHDHPAI-716: Changing default date value

modules/release-notes/ref-release-notes-new-features.adoc
=> RHIDP-4743: Fixed links post-ga

modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc, modules/authentication/proc-provisioning-users-from-microsoft-azure-to-the-software-catalog.adoc
**Version(s):** main, 1.4, 1.5
**Issue:** https://issues.redhat.com/browse/RHIDP-6560
Preview link: [4.2. Provisioning users from Microsoft Azure to the software catalog](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1020/authentication/#provisioning-users-from-microsoft-azure-to-the-software-catalog)
=> RHIDP-6560: Fix unterminated open blocks

modules/installation/proc-install-operator.adoc
1.5, 1.6
**Issue:**
https://issues.redhat.com/browse/RHIDP-6149
=> RHIDP-6149: Supported platform list in installation docs

assemblies/assembly-customizing-the-appearance.adoc, modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc, titles/customizing/master.adoc
1.5
**Issue:**
https://issues.redhat.com/browse/RHIDP-6970
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1071/customizing/#proc-customize-rhdh-sidebar-menuitems_customizing-appearance
=> RHIDP-6970: Fix headings in Customizing doc

artifacts/attributes.adoc, assemblies/dynamic-plugins/assembly-rhdh-installing-dynamic-plugins.adoc
**Version(s):** 1.3
**Issue:** https://issues.redhat.com/browse/RHIDP-5058
**Preview:** [2.1.2. Technology Preview plugins](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1040/plugin-rhdh/#rhdh-tech-preview-plugins)
=> RHIDP-5058: Update documentation references to the Ansible BU supported plug-ins

modules/configuring-the-global-header/proc-customize-rhdh-global-header.adoc
**Issue:** [RHIDP-6760](https://issues.redhat.com/browse/RHIDP-6760)
**Preview:** [6.1. Customizing your Red Hat Developer Hub global header](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1064/customizing/#customizing-your-product-global-header_configuring-the-global-header-in-rhdh)
=> RHIDP-6760: Incorrect link in Customizing RHDH Title

artifacts/attributes.adoc, assemblies/assembly-authenticating-with-rhbk.adoc, modules/authentication/proc-enabling-authentication-with-rhbk.adoc
main, 1.6.0, 1.5.x
**Issue:**
[RHIDP-7076](https://issues.redhat.com/browse/RHIDP-7076)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1083/plugins-rhdh-configure/#rhdh-keycloak_title-plugins-rhdh-configure
=> RHIDP-7076: Changing version number for RHBK

assemblies/assembly-customizing-the-appearance.adoc, modules/customizing-the-appearance/con-customize-rhdh-sidebar-menuitems.adoc, modules/customizing-the-appearance/proc-configuring-dynamic-plugin-menuitem.adoc, modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc, modules/customizing-the-appearance/proc-modifying-or-adding-rhdh-custom-menuitem.adoc
1.6, 1.5.x, main
**Issue:**
[RHIDP-6525](https://issues.redhat.com/browse/RHIDP-6525)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1056/customizing/#con-customize-rhdh-sidebar-menuitems_customizing-appearance
=> RHIDP-6525: Modularizing Customizing

modules/observe/adoption-insights/proc-install-adoption-insights.adoc
main, 1.5.x, 1.6
**Issue:**
[RHIDP-7239](https://issues.redhat.com/browse/RHIDP-7239)
**Preview:**
=> RHIDP:7239: Updated the reference for Adoption Insights

modules/observe/adoption-insights/proc-install-adoption-insights.adoc
=> Manual cherrypick for Pr-1107

modules/using-service-now/ref-supported-servicenow-custom-actions.adoc
**Issue:** https://issues.redhat.com/browse/RHIDP-6508
**Preview:**
=> RHIDP-6508 - modularize _Supported ServiceNow custom actions_

artifacts/attributes.adoc
1.6
**Issue:**
RHIDP-7292
**Preview:**
=> Updated versions for 1.6

assemblies/assembly-install-rhdh-eks-operator.adoc, modules/installation/proc-rhdh-deploy-eks-operator.adoc, titles/install-rhdh-eks/master.adoc
1.6
**Issue:**
https://issues.redhat.com/browse/RHIDP-6506
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1086/install-rhdh-eks/#assembly-install-rhdh-eks-operator
=> RHIDP-6506: Modularize proc-rhdh-deploy-eks-operator.adoc

titles/techdocs/docinfo.xml, titles/techdocs/master.adoc
1.5
**Issue:**
RHIDP-6850
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1072/techdocs/
=> RHIDP-6850: Add TechDocs subtitle

modules/dynamic-plugins/proc-installing-and-configuring-redis-cache.adoc
main, 1.6
**Issue:**
[RHIDP-6503](https://issues.redhat.com/browse/RHIDP-6503)
**Preview:**
[Configuring the Redis cache for dynamic plugins in Red Hat Developer Hub](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1087/configuring/#proc-installing-and-configuring-redis-cache_running-behind-a-proxy)
=> RHIDP-6503 - Modularize: Installing and configuring the Redis cache

artifacts/attributes.adoc
RHIDP-6575 - Add RHDH Local attributes
1.6
**Issue:**
RHIDP-6575
**Preview:**
=> RHIDP-6575 - Add RHDH Local attributes

modules/authentication/proc-enabling-authentication-with-rhbk.adoc
**Version(s):** 1.4, 1.5, 1.6, main
**Issue:** [RHIDP-7116](https://issues.redhat.com/browse/RHIDP-7116)
**Preview:** [2.1. Enabling authentication with Red Hat Build of Keycloak (RHBK)](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1139/authentication/#enabling-authentication-with-rhbk)
=> RHIDP-7116: Remove dangerouslyAllowSignInWithoutUserInCatalog in RHBK auth section

modules/release-notes/ref-release-notes-new-features.adoc, modules/release-notes/ref-release-notes-technology-preview.adoc
chore: move RHIDP-4676 from TP to new features list (RHIDP-6148)
N/A
N/A
=> chore: move RHIDP-4676 from TP to new features list (RHIDP-6148) [release-1.5]

modules/release-notes/ref-release-notes-developer-preview.adoc
**Version(s):** 1.6 
**Issue:** [RHIDP-6575](https://issues.redhat.com/browse/RHIDP-6575)
**Preview:**
=> RHIDP-6575:Minor-Fixes-RHIDP-6000-Release-notes-for-Red-Hat-Developer-Hub-1.6.0

assemblies/assembly-customizing-the-learning-paths.adoc, modules/customizing-the-learning-paths/con-about-learning-paths.adoc, modules/customizing-the-learning-paths/proc-starting-and-completing-lessions-in-learning-paths.adoc, titles/customizing/master.adoc
1.6, main
**Issue:**
[RHIDP-6147](https://issues.redhat.com/browse/RHIDP-6147)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1099/customizing/#con-about-learning-paths_configuring-templates
=> RHIDP-6147: Developer-focused content for Learning Paths

artifacts/attributes.adoc, modules/installation/proc-install-operator.adoc
1.6
**Issue:**
https://issues.redhat.com/browse/RHIDP-6152
**Preview:**
=> RHIDP-6152: Update Install Operator doc to reflect UI changes

modules/customizing-templates/proc-creating-templates.adoc
main, 1.6.x
**Issue:**
[RHIDP-7542](https://issues.redhat.com/browse/RHIDP-7542)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1178/customizing/#proc-creating-templates_configuring-templates
=> RHIDP-7542: Template Editor section update

assemblies/assembly-configuring-authorization-in-rhdh.adoc, assemblies/assembly-delegating-rbac-access-rhdh.adoc, modules/authorization/proc-delegating-rbac-access-api.adoc, modules/authorization/proc-delegating-rbac-access-webui.adoc
1.6, main
**Issue:**
[RHIDP-7461](https://issues.redhat.com/browse/RHIDP-7461)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1176/authorization/#assembly-delegating-rbac-access-rhdh_title-authorization
=> RHIDP-7461: List the steps for role-based access in UI

modules/release-notes/ref-release-notes-fixed-security-issues.adoc
**Version(s):** 1.5 
**Issue:** [RHDHBUGS-241](https://issues.redhat.com/browse/RHDHBUGS-241)
**Preview:** [7. Fixed security issues](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1190/rel-notes-rhdh/#fixed-security-issues)
=> RHDHBUGS-241: Update RHSA links for Fixed Security Issues for 1.5

modules/release-notes/ref-release-notes-fixed-issues.adoc, modules/release-notes/ref-release-notes-known-issues.adoc
This PR removes [RHIDP-7529](https://issues.redhat.com/browse/RHIDP-7529) from Known Issues category to Bug Fixes. 
**Issue:** [RHIDP-7529](https://issues.redhat.com/browse/RHIDP-7529)
**Preview:** [5.1. Fixed issues in 1.6.0](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1188/rel-notes-rhdh/#fixed-issues-in-1-6-0)
=> RHIDP-5999: Fixed Issues in RN

modules/observe/adoption-insights/proc-install-adoption-insights.adoc
main, 1.6.x, 1.5.x
**Issue:**
[RHDHPAI-813](https://issues.redhat.com/browse/RHDHPAI-813)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1191/adoption-insights/#proc-install-adoption-insights_title-adoption-insights
=> RHDHPAI-813: Updated the adoption insights image

artifacts/attributes.adoc, modules/software-catalogs/proc-adding-new-components-to-the-rhdh-instance.adoc
**Version(s):** 1.5, 1.6, main
**Issue:** [RHIDP-7649](https://issues.redhat.com/browse/RHIDP-7649)
**Preview:** 
[5.1. Adding new components to your Red Hat Developer Hub instance](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1206/customizing/#proc-adding-new-components-to-the-rhdh-instance_about-software-catalogs)
[Chapter 8. Bulk importing GitHub repositories](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html-single/configuring_dynamic_plugins/index#bulk-importing-github-repositories)
=> RHIDP-7649: Update link to Bulk importing GitHub repositories

modules/release-notes/ref-release-notes-fixed-issues.adoc
1.5
**Issue:**
https://issues.redhat.com/browse/RHIDP-6749
**Preview:**
=> RHIDP-6749: RNs for 1.5.2

modules/customizing-templates/proc-creating-templates.adoc
(Created a separate PR as the content in release-1.5 is different)
ONLY 1.5.x
**Issue:**
RHIDP-7542
**Preview:**
=> RHIDP-7542: Template editor updates

artifacts/attributes.adoc
1.5.2
**Issue:**
[RHIDP-7748 - Update release version for 1.5.2](https://issues.redhat.com/browse/RHIDP-7748)
**Preview:**
=> RHIDP-7748 - Update release version for 1.5.2

modules/customizing-templates/proc-creating-templates.adoc
main, 1.6.x
**Issue:**
RHIDP-7599, RHIDP-7436
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1218/customizing/#proc-creating-templates_configuring-templates
=> RHIDP-7599: Update Template editor

titles/about/master.adoc, titles/adoption-insights/master.adoc, titles/audit-log/master.adoc, titles/authentication/master.adoc, titles/authorization/master.adoc, titles/configuring/master.adoc, titles/customizing/master.adoc, titles/install-rhdh-air-gapped/master.adoc, titles/install-rhdh-aks/master.adoc, titles/install-rhdh-eks/master.adoc, titles/install-rhdh-gke/master.adoc, titles/install-rhdh-ocp/master.adoc, titles/install-rhdh-osd-gcp/master.adoc, titles/integrating-with-github/master.adoc, titles/monitoring-and-logging/master.adoc, titles/plugin-rhdh/title-plugin.adoc, titles/plugins-rhdh-about/master.adoc, titles/plugins-rhdh-configure/master.adoc, titles/plugins-rhdh-install/master.adoc, titles/plugins-rhdh-reference/master.adoc, titles/plugins-rhdh-troubleshooting/master.adoc, titles/plugins-rhdh-using/master.adoc, titles/techdocs/docinfo.xml, titles/telemetry/master.adoc, titles/upgrade-rhdh/master.adoc
main, 1.6.x
**Issue:**
[RHIDP-7812](https://issues.redhat.com/browse/RHIDP-7812)
**Preview:**
- About: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1232/about/
- Adoption Insights: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1232/adoption-insights/
- Audit Logs: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1232/audit-log/
- Authentication: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1232/authentication/
- Authorization: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1232/authorization/
- Configuring: https://redhat-developer.github.io/red-hat-developers-document …
=> RHIDP-7812: Updated abbrev. and added missing periods

modules/customizing-templates/proc-creating-templates.adoc
main, 1.6.x
**Issue:**
**Preview:**
=> Minor change

modules/release-notes/ref-release-notes-fixed-security-issues.adoc
=> chore(rn): Security update for 1.5.3

modules/configuring-high-availability/proc-configuring-high-availability-in-rhdh-operator-deployment.adoc, modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc, modules/customizing-techdocs/proc-techdocs-configure-odf-operator.adoc
main, 1.7, 1.6.x
**Issue:**
[RHIDP-7789](https://issues.redhat.com/browse/RHIDP-7789)
**Preview:**
=> RHIDP-7789: Some docs refer to old CRD versions or deprecated CRD fields

modules/dynamic-plugins/rhdh-supported-plugins.sh
chore: optionally provide more verbose details about which plugins are skipped from the csv generation (RHIDP-4196), so it's clear that techdocs plugins are not in the csv (but are in the supported / tech preview tables)
N/A
RHIDP-4196 (throwback to 1.4!)
N/A
=> chore: optionally provide more details about which plugins are missing from the .csv (RHIDP-4196)

modules/installation/proc-install-operator.adoc, modules/installation/proc-install-rhdh-ocp-operator.adoc, modules/installation/proc-install-rhdh-osd-gcp-helm.adoc, modules/installation/proc-install-rhdh-osd-gcp-operator.adoc, titles/install-rhdh-ocp/master.adoc, titles/install-rhdh-osd-gcp/master.adoc
**Issue:** [RHDHBUGS-314](https://issues.redhat.com/browse/RHDHBUGS-314)
**Preview:**
=> RHIDP-5733: Info about custom config in the Installation guides-manual-cherry-pick

assemblies/assembly-adoption-insights.adoc
main, 1.7.x
**Issue:**
RHIDP-7610
**Preview:**
=> Minor change in adoption insights

modules/release-notes/ref-release-notes-breaking-changes.adoc, modules/release-notes/ref-release-notes-deprecated-functionalities-extra.adoc, titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
1.7
**Issue:**
Add new command line tool as a breaking change in the release notes.
**Preview:**
=> RHIDP-6477-RN-JANUS-IDP-CLI - POST-GA docs release tasks for RHDH 1.7.0 release

modules/release-notes/ref-release-notes-new-features-extra.adoc, titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
1.7
**Issue:**
RHDHPAI-770
**Preview:**
=> RHDHPAI-770-1 - Added RHDHPAI-770 feature to the new features

artifacts/attributes.adoc, modules/observe/adoption-insights/proc-configure-adoption-insights.adoc, modules/observe/adoption-insights/proc-customize-adoption-insights.adoc, modules/release-notes/ref-release-notes-new-features.adoc
main, 1.7
**Issue:**
RHIDP-8688
**Preview:**
=> RHIDP-8688: Minor changes

artifacts/attributes.adoc, modules/observe/adoption-insights/proc-configure-adoption-insights.adoc, modules/observe/adoption-insights/proc-customize-adoption-insights.adoc, modules/release-notes/ref-release-notes-new-features.adoc
=> Manual cherrypick for PR-1324

modules/release-notes/ref-release-notes-new-features.adoc
ONLY 1.6.x
**Issue:**
RHIDP-7723
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1321/rel-notes-rhdh/#enhancement-rhidp-7723
=> RHIDP-7723: Readonlyrootfilesystem release notes update

modules/release-notes/ref-release-notes-breaking-changes.adoc
1.7.0 ONLY
**Issue:**
[RHDHBUGS-2000](https://issues.redhat.com/browse/RHDHBUGS-2000)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1346/rel-notes-rhdh/#removed-functionality-rhdhbugs-2000
=> RHDHBUGS-2000: Update the breaking change

modules/installation/proc-install-operator.adoc, modules/installation/proc-install-rhdh-helm-airgapped-full.adoc, modules/installation/proc-install-rhdh-helm-airgapped-partial.adoc, modules/installation/proc-install-rhdh-ocp-helm-gui.adoc, modules/installation/proc-install-rhdh-operator-airgapped-full.adoc, modules/installation/proc-install-rhdh-operator-airgapped-partial.adoc, modules/installation/proc-install-rhdh-osd-gcp-helm.adoc, modules/installation/proc-install-rhdh-osd-gcp-operator.adoc, modules/installation/proc-rhdh-deploy-aks-helm.adoc, modules/installation/proc-rhdh-deploy-eks-helm.adoc, modules/installation/proc-rhdh-deploy-eks-operator.adoc, modules/installation/proc-rhdh-deploy-gke-helm.adoc, modules/installation/proc-rhdh-deploy-gke-operator.adoc
=> Manual cherry-pick-1.6-Add Sizing requirements as a prereq for RHDH installation

modules/release-notes/ref-release-notes-fixed-security-issues.adoc
**Version(s):** 1.7
**Issue:** [RHIDP-8604](https://issues.redhat.com/browse/RHIDP-8604)
**Preview:**
=> RHIDP-8604: Release notes for Red Hat Developer Hub 1.7.1

assemblies/assembly-configuring-default-secret-pvc-mounts.adoc, assemblies/assembly-rhdh-default-configuration.adoc, modules/configuring-external-databases/con-automated-operator-features.adoc, modules/configuring-external-databases/con-configuring-default-secret-pvc-mounts.adoc, modules/configuring-external-databases/con-default-base-urls.adoc, modules/configuring-external-databases/con-metadata-generation.adoc, modules/configuring-external-databases/con-multiple-resources.adoc, modules/configuring-external-databases/proc-configuring-mount-paths.adoc, modules/configuring-external-databases/ref-rhdh-default-configuration.adoc, titles/configuring/master.adoc
**Version(s):** 1.7
**Issue:**
**Preview:**
[2. Red Hat Developer Hub default configuration](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1398/configuring/#assembly-rhdh-default-configuration_provisioning-and-using-your-custom-configuration)
[2.1. Red Hat Developer Hub default configuration guide](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1398/configuring/#rhdh-default-configuration)
[2.2. Automated Operator features](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1398/configuring/#con-automated-operator-features_provisioning-and-using-your-custom-configuration)
[2.3. Configuring mounts for default Secrets and Persistent Volume Claims …
=> Default configuration

assemblies/assembly-configuring-default-secret-pvc-mounts.adoc, assemblies/assembly-rhdh-default-configuration.adoc, modules/configuring-external-databases/con-automated-operator-features.adoc, modules/configuring-external-databases/con-configuring-default-secret-pvc-mounts.adoc, modules/configuring-external-databases/con-default-base-urls.adoc, modules/configuring-external-databases/con-metadata-generation.adoc, modules/configuring-external-databases/con-multiple-resources.adoc, modules/configuring-external-databases/proc-configuring-mount-paths.adoc, modules/configuring-external-databases/ref-rhdh-default-configuration.adoc, titles/configuring/master.adoc
**Issue:**
**Preview:**
[2. Red Hat Developer Hub default configuration](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1399/configuring/#assembly-rhdh-default-configuration_provisioning-and-using-your-custom-configuration)
[2.1. Red Hat Developer Hub default configuration guide](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1399/configuring/#rhdh-default-configuration)
[2.2. Automated Operator features](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1399/configuring/#con-automated-operator-features_provisioning-and-using-your-custom-configuration)
[2.3. Configuring mounts for default Secrets and Persistent Volume Claims …
=> Manual cherry-pick-#1384

assemblies/assembly-rhdh-default-configuration.adoc, modules/configuring-external-databases/con-mounts-for-default-secret-pvc-mounts.adoc, modules/configuring-external-databases/con-multiple-resources.adoc, modules/configuring-external-databases/ref-rhdh-default-configuration.adoc
**Version(s):** 1.6, 1.7, main
**Issue:** [RHDHBUGS-261](https://issues.redhat.com/browse/RHDHBUGS-261)
**Preview:**
=> RHDHBUGS-261: Minor fixes

modules/developer-lightspeed/proc-changing-your-llm-provider.adoc, modules/developer-lightspeed/proc-installing-and-configuring-lightspeed.adoc
main, 1.7.x
**Issue:**
RHDHBUGS-2051
**Preview:**
=> RHDHBUGS-2051: Adding further changes
