getting-started/proc-add-custom-app-file-openshift.adoc
getting-started/proc-add-source-control-rhdh-catalog.adoc
installation/proc-install-rhdh-helm.adoc
modules/installation/proc-install-rhdh-helm.adoc

Update instructions to be more specific and clear about how to configure the GitHub Authorization and GitHub Integration settings including where to go and how to create the OAuth App and GitHub App that are required for configuration.

Update GitHub Authorization and Integration instructions

---

installation/proc-install-rhdh-operator.adoc

Fixed CM indentation for `backend.baseUrl` and  `backend.cors.origin`

CM example indentation fix.

---

getting-started/proc-customize-rhdh-homepage.adoc

Update references and links to the `backstage-customization-provider` repository in the janus-idp org to point to the `red-hat-developer-hub-customization-provider` repository in the redhat-developers org
Fixes [RHIDP-1025](https://issues.redhat.com/browse/RHIDP-1025)

RHIDP-1025: Migrate Janus IDP customization provider repo to redhat-developers org

---

getting-started/proc-customize-rhdh-homepage.adoc

Update references and links to the backstage-customization-provider repository in the janus-idp org to point to the red-hat-developer-hub-customization-provider repository in the redhat-developers org
Cherry Picked to 1.0.x
Fixes [RHIDP-1025](https://issues.redhat.com/browse/RHIDP-1025)
https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/147

RHIDP-1025: Migrate Janus IDP customization provider repo to redhat-developers org (1.0.x)

---

getting-started/proc-customize-rhdh-homepage.adoc

Update references and links to the backstage-customization-provider repository in the janus-idp org to point to the red-hat-developer-hub-customization-provider repository in the redhat-developers org
Cherry Picked to 1.1.x
Fixes [RHIDP-1025](https://issues.redhat.com/browse/RHIDP-1025)
https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/147

RHIDP-1025: Migrate Janus IDP customization provider repo to redhat-developers org (1.1.x)

---

.gitignore
.htmltest.yml

This update adds a configuration file for htmltest to test links in user working copies.
See: https://github.com/wjdp/htmltest
To test:
1. Install htmltest from https://github.com/wjdp/htmltest
2. Run `htmltest`
Sample output (with current broken links):
```
htmltest 
htmltest started at 05:07:44 on titles-generated/main
========================================================================
admin-rhdh/index.html
Get "https://backstage-<CUSTOM_RESOURCE_NAME>-<NAMESPACE_NAME>.<OPENSHIFT_INGRESS_DOMAIN>": dial tcp: lookup backstage-<CUSTOM_RESOURCE_NAME>-<NAMESPACE_NAME>.<OPENSHIFT_INGRESS_DOMAIN>: no such host --- admin-rhdh/index.html --> https://backstage-<CUSTOM_RESOURCE_NAME>-<NAMESPACE_NAME>.<OPENSHIFT_INGRESS_DOMAIN>
Get "https://<rhdh_url>/api/auth/oidc/handler/frame": dial tcp: …
```

chore: Added HTMLtest configuration to test links

---

admin/con-rbac-rest-api.adoc
admin/proc-rbac-send-request-rbac-rest-api.adoc
admin/proc-rhdh-monitoring-logging-aws.adoc
admin/proc-using-aws-cognito-auth-provider.adoc
artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-readme.adoc
getting-started/proc-add-source-control-rhdh-catalog.adoc
getting-started/proc-configuring-github-app.adoc
getting-started/proc-customize-rhdh-homepage.adoc
getting-started/proc-customize-rhdh-tech-radar-page.adoc
getting-started/proc-registering-github-app.adoc
installation/proc-install-rhdh-operator.adoc

Fixed these broken links, mostly by deactivating the links:
```
htmltest 
htmltest started at 05:07:44 on titles-generated/main
========================================================================
admin-rhdh/index.html
Get "https://backstage-<CUSTOM_RESOURCE_NAME>-<NAMESPACE_NAME>.<OPENSHIFT_INGRESS_DOMAIN>": dial tcp: lookup backstage-<CUSTOM_RESOURCE_NAME>-<NAMESPACE_NAME>.<OPENSHIFT_INGRESS_DOMAIN>: no such host --- admin-rhdh/index.html --> https://backstage-<CUSTOM_RESOURCE_NAME>-<NAMESPACE_NAME>.<OPENSHIFT_INGRESS_DOMAIN>
Get "https://<rhdh_url>/api/auth/oidc/handler/frame": dial tcp: lookup <rhdh_url>: no such host --- admin-rhdh/index.html --> https://<rhdh_url>/api/auth/oidc/handler/frame
Get "https://<rhdh_url>": dial tcp: lookup <rhdh_url>: no such host --- …
```

fix: Fixed broken links

---

modules/rhdh-plugins-reference/assembly-rhdh-installing-dynamic-plugins.adoc
modules/rhdh-plugins-reference/rhdh-supported-plugins.adoc
titles/rhdh-plugins-reference/master.adoc

Issue:
https://issues.redhat.com/browse/RHIDP-1785
Description:
Removing unnecessary link to table.
Also taking this opportunity to clean up the filename/ID for this module so that they match. This makes it much easier to find where the content needs to be updated if a link to the content is provided in a Jira issue.
Preview link:
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-179/admin-rhdh/#rhdh-supported-plugins
/cherrypick 1.1.x
/cherrypick rhdh-1.0

RHIDP-1785: Remove unnecessary link and fix IDs

---

getting-started/assembly-auth-provider-github.adoc

Fix typo / inconsistency with GitHub name

RHIDP-2143: Fix GitHub typo

---

artifacts/attributes.adoc

Note that this is a manual update for now but once we branch for 1.2, I expect to set 1.2.0 in both the 1.2.x and main branches. ref: https://issues.redhat.com/browse/RHIDP-931

chore: latest helm and operator releases are 1.1.2

---

modules/admin/proc-rhdh-deploy-aks-using-operator.adoc

Fix for https://issues.redhat.com/browse/RHIDP-2264

RHIDP-2264 : add extra app-config configuration for AKS Operator installation procedure

---

modules/dynamic-plugins/rhdh-supported-plugins.adoc

**Versions:**
1.1+
**Jira link:**
- [RHIDP-2579](https://issues.redhat.com/browse/RHIDP-2579)
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-282/plugin-rhdh/#rhdh-supported-plugins
**Reviews:**
- QE: Not required - there is nothing to test here, SME sign off should be enough

RHIDP-2579: Update techdocs plugin to enabled by default

---

.asciidoctor/docs.css

CSS: fix code blocks overflow in admonitions
Example:

chore: fix CSS for code blocks overflow in admonitions

---

assemblies/assembly-admin-templates.adoc
modules/templates/proc-adding-templates.adoc
modules/templates/proc-creating-templates.adoc
modules/templates/ref-creating-templates.adoc

**Versions:**
1.1+
**Jira link:**
- https://issues.redhat.com/browse/RHIDP-1542
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-219/admin-rhdh/#proc-adding-templates_assembly-admin-templates
**Reviews:**

RHIDP-1542: Document adding templates

---

assemblies/assembly-enabling-authentication.adoc

**Versions:**
1.2+
**Jira:** 
https://issues.redhat.com/browse/RHIDP-2681
**Preview:** 
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-343/admin-rhdh/#enabling-authentication
**Reviews:**

RHIDP-2681: Remove unsupported auth providers

---

modules/installation/proc-add-custom-app-config-file-ocp-operator.adoc

fixes #RHIDP-3001 
Simplify for clarity Adding a custom application configuration file to OpenShift Container Platform using the Operator.
* Added one preliminary step to identify RHDH external URL.
* Simplify the step where we need to enter RHDH external URL by mentioning directly the external URL rather than more complex stuff that might happen only in upstream.
1.2
**Issue:**
fixes #RHIDP-3001 
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-348/admin-rhdh/#proc-add-custom-app-config-file-ocp-operator_assembly-install-rhdh-ocp
**Reviews:**

#RHIDP-3001 - Simplify for clarity mention of external URL

---

modules/installation/proc-add-custom-app-config-file-ocp-operator.adoc

1.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-3001
Downstream tooling does not allow reusing the same callout:
**Reviews:**

RHIDP-3001 - Fix downstream tooling bug

---

modules/admin/con-rbac-config-permission-policies-external-file.adoc
modules/admin/proc-install-operator.adoc
modules/admin/proc-rbac-send-request-rbac-rest-api.adoc
modules/admin/proc-using-azure-auth-provider.adoc
modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
modules/installation/proc-install-rhdh-ocp-operator.adoc

Fixed xref statements that broke the Pantheon build.
1.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-3042
**Reviews:**

RHIDP-3042 - fixed xref statements

---

modules/installation/proc-installing-rhdh-on-openshift-with-helm-cli.adoc

1.2 
**Issue:**
https://issues.redhat.com/browse/RHIDP-3160
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-369/admin-rhdh/#proc-installing-rhdh-on-openshift-with-helm-cli_assembly-installing-rhdh-on-ocp-by-using-the-helm-chart
**Reviews:**

RHIDP-3160: Update links in Helm CLI doc

---

modules/getting-started/proc-customize-rhdh-homepage.adoc
modules/getting-started/proc-customize-rhdh-learning-paths.adoc
modules/getting-started/proc-customize-rhdh-tech-radar-page.adoc
titles/getting-started-rhdh/title-getting-started.adoc

1.2.2
**Issue:**
https://issues.redhat.com/browse/RHIDP-2810 (Create Learning Path config content)
https://issues.redhat.com/browse/RHIDP-3141 (Revise Home page and Tech Radar page config content)
[Updated] Home page config: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-368/getting-started-rhdh/#proc-customize-rhdh-homepage_rhdh-getting-started
[Updated] Tech Radar config: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-368/getting-started-rhdh/#proc-customize-rhdh-tech-radar-page_rhdh-getting-started
[New - WIP] Learning Path config: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-368/getting-started-rhdh/#proc-customize-rhdh-learning-paths_rhdh-getting-started …

RHIDP-2810: Document Learning Path configuration

---

modules/installation/proc-install-operator.adoc

1.2, 1.1
**Issue:**
https://issues.redhat.com/browse/RHIDP-3017
**Link to docs preview:** https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-376/admin-rhdh/#assembly-installing-rhdh-on-ocp-by-using-the-operator
**Reviews:**

RHIDP-3017: Updated the installation note for clarity

---

build/scripts/build-ccutil.sh

Currently, when there is a broken ID in an xref statement, it will not break any build until we do the final build on Pantheon.
Example:
```
Running: ccutil deploy --target stage --lang en-US --doctype book --uuid 84f825c6-b193-470e-8731-62c8d4f39004
Transforming the AsciiDoc content to DocBook XML...
{{[31m[1mUnknown ID or title "proc-install-rhdh-ocp-operator_assembly-install-rhdh-ocp", used as an internal cross reference[0m}}
{{[31m[1mUnknown ID or title "proc-install-operator_admin-rhdh", used as an internal cross reference[0m}}
{{[31m[1mUnknown ID or title "proc-install-rhdh-ocp-helm_assembly-install-rhdh-ocp", used as an internal cross reference[0m}}
{{[31m[1mUnknown ID or title "proc-install-rhdh-ocp-operator_assembly-install-rhdh-ocp", used as an internal cross …
```

RHIDP-3086 - Added script to run ccutil with podman

---

artifacts/attributes.adoc

We are using `main` to preview 1.3 docs in Pantheon, so we need to update the product versions to match the Pantheon build version.
1.3
**Issue:**
**Reviews:**

RHIDP-3440 Update product version to fix broken Pantheon builds

---

.github/workflows/build-asciidoc.yml
.github/workflows/pr.yml

chore(branch): create release-1.3 branch from 1.3.x; refactor actions (RHIDP-4031)
---
Adds support for building from the new `release-1.3` branch as the 1.3.x branch is now readonly.
The purpose of this change is to support doing plugin releases from a stable branch with `multi-semantic-release` (as we do in main branch), and to keep all the repos consistent, that means refactoring them to all use `release-1.y` instead of `1.y.x` for stable branches.
See discussions in slack about this issue and please merge ASAP. 
N/A
https://issues.redhat.com/browse/RHIDP-4031
N/A
Reviewers, please …

chore(branch): create release-1.3 branch from 1.3.x; refactor actions (RHIDP-4031)

---

artifacts/attributes.adoc

With the release of 1.2.4, the docs need a quick update:
https://issues.redhat.com/browse/RHIDP-4124?jql=project%20%3D%20RHIDP%20and%20fixversion%20%3D%201.2.4

chore: tagRelease.sh: bump to 1.2.4 in 1.2.x branch

---

modules/dynamic-plugins/proc-rhdh-example-external-dynamic-plugins.adoc
modules/dynamic-plugins/rhdh-supported-plugins.csv
modules/dynamic-plugins/rhdh-supported-plugins.sh

chore: exclude techdocs from the .csv (RHIDP-4196); also fix a typo in modules/dynamic-plugins/proc-rhdh-example-external-dynamic-plugins.adoc
N/A
https://issues.redhat.com/browse/RHIDP-4196
N/A

chore: exclude techdocs from the .csv (RHIDP-4196)

---

.asciidoctor/docs.css
modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc
modules/dynamic-plugins/con-preinstalled-dynamic-plugins.template.adoc

chore(typo): remove duplicate backtick and fix CSS rendering on MacOS Safari
N/A
* remove duplicate backtick 
* fix CSS rendering on MacOS Safari
Note that the asciidoctor CSS is not used by Pantheon -- this is only for the HTML previews on https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/
N/A

chore(typo): remove duplicate backtick and fix CSS rendering on MacOS Safari

---

modules/admin/proc-rbac-config-conditional-policy-file.adoc

chore: fix rendering bug in pantheon when more than one link on the same line and no link text provided (RHIDP-4301)
N/A
https://issues.redhat.com/browse/RHIDP-4301
N/A

chore: fix rendering bug in pantheon when more than one link on the same line and no link text provided (RHIDP-4301)

---

artifacts/attributes.adoc
modules/admin/proc-using-azure-auth-provider.adoc
modules/authorization/proc-rbac-send-request-rbac-rest-api.adoc
modules/getting-started/proc-customize-rhdh-homepage.adoc
modules/upgrade/proc-upgrade-rhdh-operator.adoc

Balancing out the changes made in the manual cherrypicking for PR-617
**Updated version:** main, 1.3.x

RHIDP-3377: Balancing out the changes made in the manual cherrypicking for PR-617

---

assemblies/assembly-authenticating-with-github.adoc
modules/authentication/proc-enabling-authentication-with-github.adoc
modules/importing-repositories/procedure-enabling-the-bulk-import-from-github-feature.adoc
modules/importing-repositories/procedure-importing-multiple-repositories-from-github.adoc

@rm3l said:
> I think the most important prerequisite for Bulk Import is to configure one or more GH integrations. It doesn't rely on GH authentication.
> Also, the link points to [Enabling authentication with GitHub](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html-single/authentication/index#enabling-authentication-with-github), but there is nowhere in this page how to configure a GH integration
**Version(s):** 1.3.1
**Issue:** https://issues.redhat.com/browse/RHIDP-1925
**Link to docs preview:** https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-646/authentication/#enabling-authentication-with-github
**Reviews:**

RHIDP-1925 Fix GitHub integration procedure

---

.github/workflows/build-asciidoc.yml

**Version(s):** 1.3.1, 1.4
**Issue:** https://issues.redhat.com/browse/RHIDP-4529
**Reviews:**

RHIDP-4529 Build documentation previews on GitHub with ccutil

---

assemblies/assembly-admin-templates.adoc
assemblies/assembly-configuring-external-postgresql-databases.adoc

**Version(s):** 1.2, 1.3
**Issue:** RHIDP-3734
**Reviews:**

Updates notes on Configuring external PostgreSQL databases

---

modules/dynamic-plugins/rhdh-supported-plugins.sh

chore(dynamic plugin version checking): quieter output when the versions match
N/A
N/A

chore(dynamic plugin version checking): quieter output when the versions match

---

artifacts/attributes.adoc
assemblies/assembly-audit-log.adoc
modules/observe/proc-forward-audit-log-splunk.adoc
titles/audit-log/master.adoc

1.4
**Issue:**
[RHIDP-4570](https://issues.redhat.com/browse/RHIDP-4570)
Find the preview link within the PR
**Reviews:**

RHIDP-4570: Document how to send RHDH audit logs to Splunk

---

modules/getting-started/proc-customize-rhdh-tech-radar-page.adoc

**Issue:** RHIDP-4862
**Reviews:**

RHIDP-4862 - Update Tech Radar to 1.0

---

.asciidoctorconfig
artifacts/attributes.adoc
artifacts/snip-customer-support-info.adoc
assemblies/assembly-about-rhdh.adoc
modules/about/ref-customer-support-info.adoc
titles/about/master.adoc
titles/admin-rhdh/title-admin.adoc
titles/audit-log/master.adoc
titles/authentication/master.adoc
titles/authorization/master.adoc
titles/getting-started-rhdh/title-getting-started.adoc
titles/install-rhdh-air-gapped/master.adoc
titles/install-rhdh-aks/master.adoc
titles/install-rhdh-eks/master.adoc
titles/install-rhdh-gke/master.adoc
titles/install-rhdh-ocp/master.adoc
titles/install-rhdh-osd-gcp/master.adoc
titles/monitoring-and-logging/master.adoc
titles/plugin-rhdh/title-plugin.adoc
titles/plugins-rhdh-about/master.adoc
titles/plugins-rhdh-configure/master.adoc
titles/plugins-rhdh-install/master.adoc
titles/plugins-rhdh-reference/master.adoc
titles/plugins-rhdh-troubleshooting/master.adoc
titles/plugins-rhdh-using/master.adoc
titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
titles/telemetry/master.adoc
titles/upgrade-rhdh/master.adoc

* Change the content about support to a reference module and include in the About title.
* Remove the current preface about support from all titles.
* To avoid that the introduction paragraph has the *Preface* title, use the `article` document type, rather than `book`.
**Version(s):** 1.3.x, 1.4.x
**Issue:** https://issues.redhat.com/browse/RHIDP-5099

Include the support preface content only once in the entire doc set

---

artifacts/attributes.adoc
build/scripts/build-ccutil.sh

* Ccutil and Pantheon are not using the `:doctype:` attribute.
* Ccutil doctype defaults to `book`.
* To change the doctype with ccutil, use the CLI:
```
--doctype DOCTYPE           The document type. If no type is passed, the
type is assumed to be a book.
```

chore: ccutil to use the article doctype

---

modules/customization/proc-customize-rhdh-sidebar-menuitems.adoc

**Version(s):** 1.3.x, 1.4.x, and main
**Issue:** RHIDP-4506

RHIDP-4506: Docs sample for 'default.main-menu-items' is missing 'menuItems' field

---

modules/release-notes/single-source-release-notes.jira2asciidoc.yml

Fix the Jira search query to pick up Jiras for known issues when the issue also affects later versions.
**Issue:** see https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/773

chore: fix known issues search string

---

modules/authorization/ref-rbac-permission-policies.adoc

1.2, 1.3, 1.4, main
**Issue:**
RHIDP-4868

RHIDP-4868: Improving doc quality for Permission Policies in RHDH

---

artifacts/attributes.adoc
artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc
artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-readme.adoc
artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-user.adoc

**Issue:** Manual cherry-pick for https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/787

Add keycloak plugin 1.4 787

---

modules/dynamic-plugins/ref-community-plugins.adoc
modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
modules/dynamic-plugins/rhdh-supported-plugins.csv
modules/dynamic-plugins/rhdh-supported-plugins.sh

* chore(dynamic plugins): fix scope references for rhdh-plugins: should be @red-hat-developer-hub/ not @red/hat-developer-hub- 
* regenerate adoc and csv with the corrected links
N/A
RHIDP-5103
N/A

chore(dynamic plugins): fix scope references for rhdh-plugins: should be @red-hat-developer-hub/ not @red/hat-developer-hub-

---

artifacts/attributes.adoc

chore(support): minimum supported OCP version is 4.14, not 4.16
N/A
Error introduced in RHIDP-4929 /RHIDP-4930 via https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/721
cherry-pick of https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/808
N/A

chore(support): minimum supported OCP version is 4.14, not 4.16

---

assemblies/assembly-configuring-a-proxy.adoc
modules/configuring-a-proxy/con-understanding-the-no_proxy-exclusion-rules.adoc

Restore content added by https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/709 and removed by mistake by https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/721
**Issue:**

chore: restore content removed by mistake

---

artifacts/attributes.adoc
assemblies/assembly-about-rhdh.adoc
modules/about/con-benefits-of-rhdh.adoc
modules/about/con_integrations-in-rhdh.adoc

In this PR:
- I restructured about RHDH content
- Added content around RHTAP
- Renamed Discover to About at a couple of places
- Updated attributes to add references for RHTAP
**Version(s):** RHDH 1.4 and RHTAP 1.3
**Issue:**
[HACDOCS-1118](https://issues.redhat.com/browse/HACDOCS-1118)
**Output:**
[About](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-724/about/)

Updated about RHDH and added RHTAP content

---

artifacts/attributes.adoc
modules/release-notes/ref-release-notes-breaking-changes.adoc
modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
modules/release-notes/ref-release-notes-fixed-issues.adoc
modules/release-notes/ref-release-notes-known-issues.adoc
modules/release-notes/ref-release-notes-new-features.adoc
modules/release-notes/ref-release-notes-technology-preview.adoc

**Issue:** https://issues.redhat.com/browse/RHIDP-4579

RHIDP-4585-Release-Notes-1.4-Final-Fixes

---

modules/authorization/proc-enabling-the-rbac-plugin.adoc
modules/authorization/proc-rbac-ui-create-role.adoc
modules/authorization/proc-rbac-ui-edit-role.adoc

It would be useful to add information about configuring `pluginsWithPermission` in `app-config.yaml` since without it, available permissions will not be displayed by RBAC UI.
1.4
**Issue:**
[RHIDP-4490](https://issues.redhat.com/browse/RHIDP-4490)

RHIDP-4490: Introduce `pluginsWithPermission` information

---

modules/authentication/proc-enabling-authentication-with-github.adoc

In the docs at https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.4/html/authentication/authenticating-with-github#enabling-authentication-with-github
we provide the example
"
GITHUB_HOST_DOMAIN }}Enter your GitHub host domain: {{https://github.com/ unless you are using GitHub Enterprise.
"
This should be "github.com", not "https://github.com"
See https://redhat-internal.slack.com/archives/C05HGAR2DT5/p1736374261642889
Critical as this is incorrect documentation for installation
**Issue:** https://issues.redhat.com/browse/RHIDP-5469

RHIDP-5469 Update proc-enabling-authentication-with-github.adoc

---

artifacts/attributes.adoc
assemblies/assembly-provisioning-a-custom-configuration.adoc
modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
modules/release-notes/ref-release-notes-new-features.adoc

**Version(s):** 1.4.x, main
**Issue:** RHIDP-4780
**Preview link:** https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-842/configuring/#mounting-additional-files-in-your-custom-configuration-using-rhdh-operator
(This is showing the new procedure as Chapter 2, but it's supposed to be under 1.2. So, technically, as Chapter 1.2.1.. I've made the correction in the second commit but for some reason it isn't reflecting in the preview link)

RHIDP-4780: Document per-ConfigMap/Secret configuration of mountPath

---

modules/release-notes/ref-release-notes-breaking-changes.adoc
modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
modules/release-notes/ref-release-notes-known-issues.adoc
modules/release-notes/ref-release-notes-new-features.adoc

**Issue:** https://issues.redhat.com/browse/RHIDP-5458

Fix release notes links

---

artifacts/rhdh-plugins-reference/tekton/tekton-plugin-admin.adoc
artifacts/rhdh-plugins-reference/tekton/tekton-plugin-readme.adoc
artifacts/rhdh-plugins-reference/topology/topology-plugin-readme.adoc
modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
modules/customizing-techdocs/proc-techdocs-using-odf-storage.adoc
modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
modules/installation/proc-rhdh-deploy-aks-helm.adoc
modules/installation/proc-rhdh-deploy-eks-operator.adoc

Hey RHDH team. I was just reviewing these docs since our platform team is doing some discovery on using RHDH internally at Red Hat to support our department (UXE). I bumped into a couple of typos that I thought I may as well help out with. I hope this helps!

Fix some typos in RHDH documentation adocs

---

modules/configuring/proc-provisioning-your-custom-configuration.adoc

**Issue:**  https://issues.redhat.com/browse/RHIDP-5373

RHIDP-5373: Setting baseUrl

---

modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc
modules/configuring-a-proxy/proc-configuring-proxy-in-operator-deployment.adoc
modules/configuring-deployment/proc-configuring-deployment-by-using-the-operator.adoc
modules/configuring-external-databases/proc-configuring-postgresql-instance-using-the-operator.adoc
modules/configuring-external-databases/proc-migrating-databases-to-an-external-server.adoc
modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
modules/customizing-techdocs/proc-techdocs-configure-odf-operator.adoc
modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc
modules/dynamic-plugins/proc-topology-configure.adoc
modules/installation/proc-deploy-rhdh-instance-eks.adoc
modules/installation/proc-deploy-rhdh-instance-gke.adoc
modules/installation/proc-rhdh-deploy-aks-operator.adoc
modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc
modules/observe/proc-customizing-telemetry-segment-using-operator.adoc
modules/observe/proc-disabling-telemetry-using-operator.adoc
modules/observe/proc-enabling-telemetry-using-operator.adoc

1.4, main
**Issue:**
RHIDP-5374

RHIDP-5374: Consistent mentions to the product custom resource

---

modules/release-notes/ref-release-notes-breaking-changes.adoc
modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
modules/release-notes/ref-release-notes-fixed-issues.adoc
modules/release-notes/ref-release-notes-known-issues.adoc
modules/release-notes/ref-release-notes-new-features.adoc

chore: release note updates: 
* remove RHIDP-5308 (dupe of RHIDP-5319, affects 1.5); 
* add RHIDP-5734 for GKE support; 
* Judy's copy update for RHIDP-5344; 
* dedupe RHIDP-5342 vs RHIDP-5344; 
* temporarily remove RHIDP-4695 as it's not quite done
You can ignore whitespace changes at https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/887/files?w=1 (?w=1 suffix) so that you're not wondering about all the line ending diffs
N/A
N/A

chore: release note updates for GKE support and other misc updates

---

modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc
modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc

1.4.x, main
**Issue:**
[RHIDP-5725](https://issues.redhat.com/browse/RHIDP-5725)
**Preview link:** https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-883/customizing/#customizing-the-home-page

RHIDP-5725: Incorrect plugin name in the Customizing the Home page cards code snippet

---

modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc
modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc

Creating a separate PR to main, as a manual "cherrypick" for #883 .

CP to main for PR-883

---

modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc
modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
modules/installation/proc-deploy-rhdh-instance-gke.adoc
modules/installation/proc-rhdh-deploy-aks-operator.adoc

**Version(s):** 1.4, 1.5 
**Issue:** https://issues.redhat.com/browse/RHIDP-5881

Fix inconsistencies with referencing my-rhdh-secrets

---

modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc

**Version(s):** main, 1.4.x, 1.5
**Issue:** RHIDP-5592

RHIDP-5592:Wrong definition of Service Monitor for an RHDH instance by the Operator

---

titles/about/master.adoc

Changing the outlook from 
to something like what we have here, 
**Version(s):** 1.4, 1.3
**Issue:**

Change the layout of the next steps

---

modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc
modules/configuring-external-databases/proc-migrating-databases-to-an-external-server.adoc
modules/dynamic-plugins/proc-create-plugin-tgz-file.adoc
modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc

1.5, main
**Issue:**
[RHIDP-3206](https://issues.redhat.com/browse/RHIDP-3206)
**Preview links for two instances:**
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-946/configuring/#proc-configuring-postgresql-instance-using-helm_configuring-external-postgresql-databases
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-946/configuring/#proc-migrating-databases-to-an-external-server_configuring-external-postgresql-databases

RHIDP-3206: Added attribute declaration to the relevant source code block

---

modules/release-notes/ref-release-notes-new-features.adoc

RHIDP-6274 update 1.4.2 release notes

---

modules/authentication/proc-enabling-authentication-with-github.adoc
modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
modules/authentication/proc-enabling-authentication-with-rhbk.adoc

**Issue:** https://issues.redhat.com/browse/RHIDP-5491
Depends on: https://github.com/backstage/backstage/pull/27821/

RHIDP-5491 configure expiry on refresh token cookie

---

modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc
modules/dynamic-plugins/proc-install-plugins-using-custom-npm-registry.adoc
modules/dynamic-plugins/proc-load-plugin-js-package.adoc

**Version(s):** main, 1.4, 1.5
**Issue:** https://issues.redhat.com/browse/RHIDP-6130
Preview links: 
[2.2. Configuring an external PostgreSQL instance using the Helm Chart](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-962/configuring/#proc-configuring-postgresql-instance-using-helm_configuring-external-postgresql-databases)
[1.3. Installing dynamic plugins in an air-gapped environment](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-962/plugins-rhdh-install/#proc-install-plugins-using-custom-npm-registry)
[2.3.3. Loading a plugin packaged as a JavaScript package](https://redhat-developer.github.io/red-hat-developers-documentat …

RHIDP-6130: Update docs to refer to new secret name

---

modules/dynamic-plugins/con-dynamic-plugins-cache.adoc
modules/dynamic-plugins/con-install-dynamic-plugin-helm.adoc

RHIDP-5605  - Plugin installation documentation improvement for adding 'forceDownload' field
1.5
**Issue:**
[RHIDP-5605](https://issues.redhat.com/browse/RHIDP-5605)
**Previews:**
[Configuring the dynamic plugins cache](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-988/configuring/#configuring-the-dynamic-plugins-cache)
[Installing dynamic plugins using the Helm chart](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-988/plugins-rhdh-install/#con-install-dynamic-plugin-helm_rhdh-installing-rhdh-plugins)

RHIDP-5605  - Plugin installation documentation improvement for adding 'forceDownload' field

---

modules/dynamic-plugins/con-dynamic-plugins-cache.adoc

**Manual cherry-pick of #919**
main
**Issue:**
[RHIDP-5570](https://issues.redhat.com/browse/RHIDP-5570)
**Preview:**
[7.1. Enabling the dynamic plugins cache](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-998/configuring/#enabling-the-dynamic-plugins-cache)

RHIDP-5570-2 - Document that the Dynamic Plugin cache PVC is disabled by default

---

modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
modules/configuring/proc-provisioning-your-custom-configuration.adoc
modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
modules/customizing/proc-customizing-the-backend-secret.adoc
modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc
modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
modules/installation/proc-deploy-rhdh-instance-eks.adoc
modules/installation/proc-deploy-rhdh-instance-gke.adoc
modules/installation/proc-rhdh-deploy-aks-operator.adoc

**Issue:** https://issues.redhat.com/browse/RHIDP-5881
Preview: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-944/

RHIDP-5881: Fix inconsistencies with referencing my-rhdh-secrets

---

assemblies/assembly-configuring-the-global-header.adoc
modules/configuring-the-global-header/proc-customize-rhdh-global-header.adoc
modules/configuring-the-global-header/proc-mount-points.adoc
titles/customizing/master.adoc

**Version(s):** main, 1.5
**Issue:** https://issues.redhat.com/browse/RHIDP-5490
Preview: [6. Configuring the global header in Red Hat Developer Hub](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-954/customizing/#configuring-the-global-header-in-rhdh)

RHIDP-5490: Configure global header in RHDH

---

modules/release-notes/ref-release-notes-developer-preview.adoc
titles/rel-notes-rhdh/title-rhdh-release-notes.adoc

RHDHPAI-510: Adoption insights DP feature in 1.5 RNs

---

modules/dynamic-plugins/con-ansible-plugin-admin.adoc

1.4
**Issue:**
https://issues.redhat.com/browse/RHIDP-6550
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1013/plugins-rhdh-configure/#installing-ansible-plug-ins-for-red-hat-developer-hub
**Reviews:**
* Update the link to the AAP docs for the Ansible plug-ins.
* Remove the tech preview status for the Ansible plug-ins.

RHIDP-6550 Update URL for Ansible plug-ins docs

---

modules/observe/adoption-insights/proc-install-adoption-insights.adoc

1.5, main
**Issue:**
[RHDHPAI-720](https://issues.redhat.com/browse/RHDHPAI-720)

RHDHPAI-720: Adding more info to the app-config-dynamic.yaml file in the install section

---

assemblies/assembly-techdocs-addons-installing.adoc
assemblies/assembly-techdocs-addons.adoc

1.5.0 / 1.5.1
**Issue:**
[RHIDP-6667](https://issues.redhat.com/browse/RHIDP-6667)

RHIDP-6667: Update TechDocs add-ons doc

---

modules/customizing-the-appearance/proc-customize-rhdh-branding-logo.adoc

**Version(s):** 1.4, 1.5, 1.6, main
**Issue:** https://issues.redhat.com/browse/RHIDP-3504
Preview link: [9.2. Customizing the branding logo of your Developer Hub instance](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1033/customizing/#proc-customize-rhdh-branding-logo_customizing-appearance)

RHIDP-3504: Update the doc on changing RHDH logo

---

modules/release-notes/ref-release-notes-breaking-changes.adoc
modules/release-notes/ref-release-notes-deprecated-functionalities.adoc

1.5.x
**Issue:**
[RHIDP-6845](https://issues.redhat.com/browse/RHIDP-6845)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1053/rel-notes-rhdh/#breaking-change-rhidp-5958

RHIDP-6845: Move dangerouslyAllowSignInWithoutUserInCatalog from Deprecated to Breaking changes section

---

modules/release-notes/ref-release-notes-breaking-changes.adoc

**Issue:** https://issues.redhat.com/browse/RHDHBUGS-232
**Preview:** [2.3. The dynamicPlugins.cache.volumeClaimSpec field is removed from the Helm Chart, dynamic plugin storage is now ephemeral by default](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1078/rel-notes-rhdh/#breaking-change-rhidp-5568)

RHDHBUGS-232: Changes to RHDH 1.5 release notes

---

modules/observe/adoption-insights/con-about-adoption-insights.adoc
modules/observe/adoption-insights/proc-configure-adoption-insights.adoc
modules/observe/adoption-insights/proc-install-adoption-insights.adoc
modules/observe/adoption-insights/proc-viewing-adoption-insights-card.adoc

1.5.x, main, 1.6
**Issue:**
[RHDHPAI-735](https://issues.redhat.com/browse/RHDHPAI-735)
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1060/adoption-insights/

RHDHPAI-735: Configuration info and other issues to fix

---

modules/authentication/proc-enabling-authentication-with-rhbk.adoc

RHBK authentication: sub claim OIDC resolver is default
**Version(s):** release-1.6
**Issue:**  https://issues.redhat.com/browse/RHIDP-6882
**Preview:**

RHIDP-6882 - RHBK authentication: sub claim OIDC resolver is default

---

assemblies/assembly-configuring-authorization-in-rhdh.adoc
modules/authorization/proc-delegating-rbac-access.adoc
modules/authorization/ref-rbac-permission-policies.adoc

1.6
**Issue:**
[RHIDP-6570](https://issues.redhat.com/browse/RHIDP-6570)
**Preview:**

RHIDP-6570: Document the permission support to RBAC plugin

---

modules/configuring/proc-provisioning-your-custom-configuration.adoc

on Operator-based deployments configuring the base URL is no longer required
**Version(s):** 
/cherry-pick release-1.6
**Issue:** 
https://issues.redhat.com/browse/RHIDP-6571
https://issues.redhat.com/browse/RHIDP-6174
https://issues.redhat.com/browse/RHIDP-6670
**Preview:**

RHIDP-6571 - remove configuring the base URL for Operator-based

---

assemblies/assembly-configuring-default-secret-pvc-mounts.adoc
modules/configuring-external-databases/proc-configuring-mount-paths.adoc
modules/configuring-external-databases/proc-mounting-to-specific-containers.adoc
titles/configuring/master.adoc

**Version(s):** main, 1.5
**Issue:** https://issues.redhat.com/browse/RHIDP-5515
**Related PR with both Peer and Technical Reviews, Comments and Suggestions: [PR-1024](https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/1024)**
Preview link: [9. Configuring default mounts for Secrets and PVCs](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1067/configuring/#assembly-configuring-default-secret-pvc-mounts_running-behind-a-proxy)

RHIDP-5515: Document default PVC and Secret configuration update

---

assemblies/assembly-techdocs-add-docs.adoc
assemblies/assembly-using-techdocs.adoc
modules/techdocs/proc-techdocs-add-doc-github.adoc
modules/techdocs/proc-techdocs-add-docs-from-remote-repo.adoc
modules/techdocs/proc-techdocs-edit-docs.adoc
modules/techdocs/proc-techdocs-find-docs.adoc
modules/techdocs/proc-techdocs-view-docs.adoc
titles/techdocs/master.adoc

1.6
**Issue:**
https://issues.redhat.com/browse/RHIDP-6146
**Preview:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1082/techdocs/#assembly-using-techdocs

RHIDP-6146: Create developer-focused TechDocs content

---

assemblies/assembly-configuring-authorization-in-rhdh.adoc
titles/authentication/master.adoc
titles/authorization/master.adoc

1.4, 1.5, 1.6
**Issue:**
[RHIDP-5483](https://issues.redhat.com/browse/RHIDP-5483)

RHIDP-5483: Update Authorization Preface

---

modules/observe/adoption-insights/con-about-adoption-insights.adoc
modules/observe/adoption-insights/proc-configure-adoption-insights.adoc

Manual cherrypick for #PR-1060

Manual cherrypick for Pr-1060

---

modules/release-notes/ref-release-notes-developer-preview.adoc
titles/rel-notes-rhdh/title-rhdh-release-notes.adoc

This is a clone of [PR-1097](https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/1097/files#diff-e3a7e67aecf3b2297b7a0e8c8f5865dbc966dbef92244be175f21876c05bc4e9) which was previously reviewed, approved and merged. It turns out the RNs script does not handle Developer Preview type, so we've had to manually reinstate this section that was previously removed in PR-1097.
1.6, main
**Issue:**
RHIDP-6575
**Preview:**
[Developer Preview: RHDH Local](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1141/rel-notes-rhdh/#developer-preview)

RHIDP-6575-1 - Promote RHDH-local to Dev preview status in RHDH Docs

---

modules/release-notes/single-source-release-notes.jira2asciidoc.yml

chore: add developer-preview.adoc as a separate query and template than ref-release-notes-technology-preview.adoc
N/A
[RHIDP-6000](https://issues.redhat.com/browse/RHIDP-6000)
N/A

chore: add developer-preview.adoc as a separate query and template than ref-release-notes-technology-preview.adoc (RHIDP-6000) [release-1.6]

---

modules/customizing-the-appearance/proc-configuring-dynamic-plugin-menuitem.adoc
modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
modules/customizing-the-appearance/proc-modifying-or-adding-rhdh-custom-menuitem.adoc

**Note:** Replaces PR #1091 and includes modularization from PR #948
main, 1.6
**Issue:**
[RHIDP-6569](https://issues.redhat.com/browse/RHIDP-6569)
**Preview:**
[Customizing the sidebar menu items for your Developer Hub instance](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1150/customizing/#con-customize-rhdh-sidebar-menuitems_customizing-appearance)

RHIDP-6569-1 - Document the configurable features of navigation (sidebar) in RHDH

---

modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc

chore: fix list of enabled-by-default plugins in 1.5 (missing GA global-floating-action-button and 3 TP marketplace plugins)
N/A
N/A

chore: fix list of enabled-by-default plugins in 1.5 (missing GA global-floating-action-button and 3 TP marketplace plugins)

---

assemblies/assembly-configuring-a-floating-action-button.adoc
modules/configuring-a-floating-action-button/proc-configuring-floating-action-button-as-a-dynamic-plugin.adoc
modules/configuring-a-floating-action-button/ref-floating-action-button-parameters.adoc

**Version(s):** 1.5, 1.6, main
**Issue:** [RHIDP-6498](https://issues.redhat.com/browse/RHIDP-6498)
**Preview:** [8. Configuring a floating action button in Red Hat Developer Hub](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1180/customizing/#configuring-a-floating-action-button)
Old PR: [PR-1174](https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/1174)

RHIDP-6498: Modularize modules/configuring-a-floating-action-button/proc-configuring-floating-action-button-as-a-dynamic-plugin.adoc

---

assemblies/assembly-enabling-authentication.adoc
modules/authentication/con-understanding-authentication-and-user-provisioning.adoc

**Version(s):** 1.6, 1.7
**Issue:** https://issues.redhat.com/browse/RHIDP-6735
**Preview:**

RHIDP-6735 - Added high-level overview of auth and user provisioning

---

artifacts/attributes.adoc
modules/about/con-integrations-in-rhdh.adoc

MPORTANT: Do Not Merge - To be merged by Docs Team Only
Version(s):
main, 1.6.x
Issue:
[HACDOCS-1364](https://issues.redhat.com/browse/HACDOCS-1364)

Renamed RHTAP to RHADS

---

modules/release-notes/ref-release-notes-fixed-issues.adoc

chore: regen release notes for 1.6.2
N/A
N/A
[5.1. Fixed issues in 1.6.2](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1244/rel-notes-rhdh/#fixed-issues-in-1-6-2)

chore: regen release notes for 1.6.2

---

modules/release-notes/README.adoc

chore: add note about correctly sequencing the versions on https://issues.redhat.com/projects/RHIDP?selectedItem=com.atlassian.jira.jira-projects-plugin%3Arelease-page&status=released-unreleased as prereq for using the python queries for Release Notes generation
N/A
N/A

chore: add note about correctly sequencing of versions to allow > and < queries to work when generating Release Notes content

---

modules/dynamic-plugins/proc-create-plugin-js-package.adoc
modules/dynamic-plugins/proc-create-plugin-oci-image.adoc
modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
modules/dynamic-plugins/ref-example-third-party-plugin-installation.adoc
modules/proc-create-plugin.adoc
modules/techdocs/proc-techdocs-addon-install-third-party.adoc

1.7
**Issue:**
https://issues.redhat.com/browse/RHIDP-6966
https://issues.redhat.com/browse/RHIDP-7571
**Preview:**
[Packaging and publishing third-party plugins as dynamic plugins](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1258/plugins-rhdh-install/#assembly-package-publish-third-party-dynamic-plugin)

RHIDP-6966: use @red-hat-developer-hub/cli instead of @janus-idp/cli

---

modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc

Manual cherrpick for PR-1396

---

artifacts/attributes.adoc
assemblies/assembly-customizing-developer-lightspeed.adoc
modules/developer-lightspeed/proc-changing-your-llm-provider.adoc
modules/developer-lightspeed/proc-installing-and-configuring-lightspeed.adoc

main, 1.7.x
**Issue:**
[RHDHBUGS-2051](https://issues.redhat.com/browse/RHDHBUGS-2051)
**Preview:**
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1403/developer-lightspeed/#customizing-developer-lightspeed
- https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1403/developer-lightspeed/#proc-installing-and-configuring-lightspeed_developer-lightspeed

RHDHBUGS-2051: Adding a new topic on adding a new llm provider

---

modules/release-notes/ref-release-notes-fixed-issues.adoc
modules/release-notes/ref-release-notes-known-issues.adoc
modules/release-notes/ref-release-notes-new-features.adoc

**Version(s):** 1.7
**Issue:**
**Preview:**
[6.1. Fixed issues in 1.7.1](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1427/rel-notes-rhdh/#fixed-issues-in-1-7-1)
[1.3. Full support for Adoption Insights plugins](https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-1427/rel-notes-rhdh/#enhancement-rhdhbugs-1981)

RHDHBUGS-Fixed Issues and Feature Enhancements-1.7.1
